#!/usr/bin/env python3
"""Rebuild caremate-admin-portal/data/learn.json: 15 topics × 10 categories, ≥100 words each."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "learn.json"

DISCLAIMER = (
    "This article is for general health education and does not replace personal medical advice. "
    "If you are unsure or feel seriously unwell, contact a qualified clinician or emergency services."
)

# Each topic: id, title, summary, list of teaching points (combined into ≥100-word prose).
TOPICS: dict[str, list[tuple[str, str, str, list[str]]]] = {
    "prevention": [
        ("evergreen-prevention-1", "Sleep as everyday prevention",
         "Consistent sleep supports immunity, mood, and metabolic health.",
         ["Most adults do better with seven to nine hours most nights.",
          "Keep a steady bedtime and wake time, including weekends when you can.",
          "A darker cooler room and less caffeine after mid-afternoon help.",
          "Limit bright screens in the last hour before bed.",
          "Loud snoring, gasping, or heavy daytime sleepiness deserve a clinic mention.",
          "Sleep problems pair often with high blood pressure and weight concerns."]),
        ("evergreen-prevention-2", "Move most days, even in short bursts",
         "Regular activity protects the heart, joints, and mental health.",
         ["Aim for about 150 minutes of moderate activity weekly if safe for you.",
          "Brisk walking, dancing, cycling, and active chores all count.",
          "Spread sessions across the week instead of one exhausting day.",
          "Add simple strength work twice weekly, such as sit-to-stands.",
          "Break long sitting with short standing or walking breaks.",
          "Stop for chest pain, severe breathlessness, or unusual dizziness."]),
        ("evergreen-prevention-3", "Hand hygiene that prevents infections",
         "Soap, water, and key moments cut the spread of many germs.",
         ["Wash with soap for at least twenty seconds at key moments.",
          "Wash before eating and after toilet use or caring for someone ill.",
          "Dry hands fully; damp hands spread germs more easily.",
          "Use alcohol rub when soap is unavailable and hands look clean.",
          "Avoid touching eyes, nose, and mouth with unwashed hands.",
          "Model the habit for children at home and in shared spaces."]),
        ("evergreen-prevention-4", "Vaccines and boosters for adults",
         "Immunization needs continue after childhood.",
         ["Adults may need tetanus, influenza, COVID-19, hepatitis, or other vaccines.",
          "Needs depend on age, pregnancy, work, travel, and long-term conditions.",
          "Bring any vaccine record to avoid gaps and duplicate doses.",
          "Pregnancy and chronic disease can change recommendations.",
          "Mild arm soreness after shots is common and usually settles.",
          "Seek care for breathing trouble, hives, or facial swelling after vaccination."]),
        ("evergreen-prevention-5", "Sun, heat, and skin protection",
         "Outdoor habits lower burn, heat strain, and some skin cancer risk.",
         ["Seek shade in peak midday sun when you can.",
          "Wear a hat, sunglasses, and lightweight long sleeves outdoors.",
          "Use broad-spectrum sunscreen and reapply after sweat or swimming.",
          "Drink water often in hot weather, especially with outdoor work.",
          "Dizziness, confusion, or stopping sweat can signal heat emergency.",
          "Check skin monthly for new or changing moles and non-healing sores."]),
        ("evergreen-prevention-6", "Oral health beyond brushing once",
         "Gums and teeth affect comfort, nutrition, and wider health talks.",
         ["Brush twice daily with fluoride toothpaste.",
          "Clean between teeth with floss or interdental brushes.",
          "Replace toothbrushes every few months or after illness.",
          "Limit frequent sugary snacks and drinks that bathe teeth in sugar.",
          "See dental care for pain, swelling, bleeding gums, or loose teeth.",
          "People with diabetes should pay special attention to gum health."]),
        ("evergreen-prevention-7", "Safe drinking water and food basics",
         "Everyday choices prevent many stomach infections.",
         ["Use sealed, boiled, or treated water when tap quality is uncertain.",
          "Avoid ice of unknown origin while traveling.",
          "Cook meats thoroughly and separate raw from cooked foods.",
          "Refrigerate leftovers promptly and wash hands before food prep.",
          "Seek care for bloody diarrhea, high fever, or clear dehydration.",
          "Oral rehydration solution replaces fluids and salts in milder illness."]),
        ("evergreen-prevention-8", "Know your numbers: BP, sugar, weight",
         "A few metrics help you and your clinician act early.",
         ["Track blood pressure, indicated blood sugar, waist size, and weight trends.",
          "Use validated home monitors with consistent technique.",
          "Sit quietly before blood pressure checks with arm at heart level.",
          "Log dates and share patterns at appointments, not only single spikes.",
          "Unexplained large weight changes deserve timely review.",
          "Very high readings with symptoms need urgent clinical attention."]),
        ("evergreen-prevention-9", "Tobacco, alcohol, and harm reduction",
         "Cutting back protects lungs, liver, heart, sleep, and cancer risk.",
         ["No tobacco product is safe for lung or heart health.",
          "Ask about nicotine replacement, medicines, and counseling to quit.",
          "If you drink, stay within local low-risk guidelines.",
          "Avoid binge drinking and never drink and drive.",
          "Skip alcohol in pregnancy and with interacting medicines.",
          "Keep homes and cars smoke-free to protect children and adults."]),
        ("evergreen-prevention-10", "Stress routines that protect health",
         "Chronic stress shows up in sleep, blood pressure, and resilience.",
         ["Short daily practices help: walking, slow breathing, prayer, or journaling.",
          "Protect small rest blocks the way you protect important meetings.",
          "Social connection and morning outdoor light support mood and sleep.",
          "Limit late-night news scrolling when it leaves you tense.",
          "Seek mental health support when worry or low mood disrupt life.",
          "Asking for help early is prevention, not failure."]),
        ("evergreen-prevention-11", "Workplace and commute safety habits",
         "Injuries and fatigue often come from rushed routines.",
         ["Use seat belts and appropriate helmets; avoid phones while driving.",
          "Leave extra travel time so speed is not the default under pressure.",
          "Set desks and screens so wrists and necks stay comfortable.",
          "Lift with bent knees and keep loads close; ask for help when heavy.",
          "Know workplace first-aid points and keep emergency contacts updated.",
          "Plan recovery sleep after night shifts whenever possible."]),
        ("evergreen-prevention-12", "Hearing and vision checks over time",
         "Senses change gradually—screening catches treatable problems.",
         ["Book eye checks for blur, diabetes, eye pain, or reading trouble.",
          "Sudden floaters with flashes need prompt review.",
          "Children need vision screening in school and clinic routines.",
          "Protect hearing around loud machinery, generators, and music events.",
          "Ask for hearing review if conversations are hard in noisy rooms.",
          "Sudden vision loss is an emergency until proven otherwise."]),
        ("evergreen-prevention-13", "Mosquito and vector bite prevention",
         "Nets, screens, and water control cut malaria and related risks.",
         ["Sleep under insecticide-treated nets in malaria areas.",
          "Repair screens and empty containers that hold stagnant water.",
          "Wear longer sleeves at dusk when bites often increase.",
          "Use repellents recommended as safe for children or pregnancy.",
          "Seek care for fever after travel to malaria regions, even weeks later.",
          "Community clean-ups and covered water storage help everyone."]),
        ("evergreen-prevention-14", "Sexual health and consent basics",
         "Respect, communication, and testing protect partners and fertility.",
         ["Consent must be clear and can be withdrawn at any time.",
          "Discuss contraception and infection prevention before sex.",
          "Condoms reduce many infection risks when used correctly every time.",
          "Get tested with new partners, symptoms, or pregnancy plans.",
          "Many infections are treatable; delays can harm fertility and newborns.",
          "Ask about HPV, hepatitis B, and local confidential clinic services."]),
        ("evergreen-prevention-15", "Build a simple personal health kit",
         "A small kit supports minor issues without delaying emergencies.",
         ["Keep oral rehydration salts, a thermometer, plasters, and gauze together.",
          "Store antiseptic and personal medicines away from children.",
          "Check expiry dates twice a year and replace what is out of date.",
          "Include a written list of allergies, medicines, and emergency contacts.",
          "That list helps responders if you cannot speak for yourself.",
          "Know local emergency numbers; kits never replace urgent care for stroke or chest pain."]),
    ],
    "conditions": [
        ("evergreen-heart-1", "Know your blood pressure numbers",
         "Understanding systolic and diastolic readings helps you spot risk early.",
         ["Blood pressure is written as systolic over diastolic.",
          "Many adults aim near 120/80 mmHg; your target may differ.",
          "Check at similar times, sit quietly, and support the arm at heart level.",
          "Keep a dated log and share patterns at appointments.",
          "Severe headache, chest pain, or breathlessness with very high readings needs urgent care.",
          "Salt reduction, activity, less alcohol, no smoking, and sleep support healthier numbers."]),
        ("evergreen-heart-2", "Everyday habits that protect your heart",
         "Small daily choices add up for long-term cardiovascular health.",
         ["Consistent habits beat short intense bursts of change.",
          "Aim for 150 minutes of moderate activity weekly if safe.",
          "Fill plates with vegetables, fruits, beans, and whole grains when you can.",
          "Prefer healthier fats like nuts and fish; cut sugary drinks.",
          "Ask about screening if you have diabetes, high cholesterol, or family history.",
          "Do not stop prescribed heart medicines without medical advice."]),
        ("evergreen-heart-3", "Chest pain: when to seek help fast",
         "Some chest discomfort needs emergency care even if you feel unsure.",
         ["Call emergency services for crushing pressure-like chest pain.",
          "Pain spreading to arm, jaw, or back is a warning sign.",
          "Sweating, nausea, dizziness, or severe breathlessness raise urgency.",
          "Women and older adults may notice fatigue or indigestion-like discomfort.",
          "Do not drive yourself if you suspect a heart emergency.",
          "Sit or lie down and follow dispatcher instructions while waiting."]),
        ("evergreen-heart-4", "Salt, fluid, and heart strain",
         "Too much salt can raise blood pressure and make the heart work harder.",
         ["Most salt comes from packaged foods and restaurant meals.",
          "Cooking at home and reading labels help you cut back gradually.",
          "Heart failure or kidney disease may also need fluid limits.",
          "Report sudden weight gain, swelling, or worse breathlessness.",
          "Flavor food with herbs, citrus, garlic, and spices.",
          "Ask what daily salt target fits your conditions and medicines."]),
        ("evergreen-heart-5", "Cholesterol basics in plain language",
         "LDL, HDL, and triglycerides each play a different role in heart risk.",
         ["High LDL contributes to plaque in arteries.",
          "HDL helps carry cholesterol away from artery walls.",
          "Triglycerides rise with excess sugar, alcohol, and low activity.",
          "Lipid results are read with blood pressure, smoking, and family history.",
          "Diet, exercise, and medicines can improve numbers.",
          "Do not stop statins just because you feel well."]),
        ("evergreen-infectious-1", "Hand hygiene that actually works",
         "Soap, water, and key moments cut transmission of many infections.",
         ["Wash twenty seconds before eating and after toilet use.",
          "Wash after coughing into hands or caring for someone ill.",
          "Dry thoroughly; use alcohol rub when hands look clean but soap is missing.",
          "Avoid touching your face with unwashed hands in clinics and transit.",
          "Protect infants and older adults in your household with the same habit.",
          "Make hand hygiene a shared family routine, not one person’s chore."]),
        ("evergreen-infectious-2", "Cough and sneeze etiquette",
         "Covering correctly protects the people around you.",
         ["Cough or sneeze into a tissue or your elbow, not bare palms.",
          "Dispose of tissues and wash hands afterward.",
          "Stay home with fever or heavy cough when you can.",
          "Protect infants and older adults from close exposure when ill.",
          "Masks help in crowded indoor spaces when you are sick.",
          "Kind communication reduces stigma around staying home."]),
        ("evergreen-infectious-3", "When a cold might be something more",
         "Duration, breathing trouble, and high fever change the plan.",
         ["Most colds improve within a week with rest and fluids.",
          "Seek care for trouble breathing, chest pain, or confusion.",
          "Persistent high fever or sudden worsening needs review.",
          "Infants, pregnant people, and immunocompromised adults are higher risk.",
          "Antibiotics are not routine for uncomplicated viral colds.",
          "Ask about testing when influenza, COVID-19, or malaria is circulating."]),
        ("evergreen-infectious-4", "Food and water precautions while traveling",
         "Simple choices reduce traveler’s diarrhea and related infections.",
         ["Prefer sealed bottled or boiled water when tap water is uncertain.",
          "Avoid ice of unknown origin and raw foods washed in unsafe water.",
          "Choose hot thoroughly cooked meals and peel fruits yourself.",
          "Pack oral rehydration supplies for the trip.",
          "Know where to seek care if vomiting and diarrhea become severe.",
          "Travel clinics advise vaccines and malaria prevention by destination."]),
        ("evergreen-infectious-5", "Adult vaccines beyond childhood schedules",
         "Immunization continues through adult life.",
         ["Ask which adult vaccines you are due for at clinic visits.",
          "Jobs, travel, pregnancy, and chronic disease change the list.",
          "Keep a personal vaccine record on paper or phone.",
          "Records prevent missed doses and unnecessary duplicates.",
          "Mild arm soreness after vaccination is common.",
          "Seek urgent care for severe allergic symptoms after a shot."]),
        ("evergreen-conditions-6", "Living with type 2 diabetes day to day",
         "Steady habits and monitoring reduce complications over years.",
         ["Type 2 diabetes means insulin does not work well enough.",
          "Meal timing, fiber-rich foods, activity, and medicines work together.",
          "Learn your glucose targets and signs of lows such as shakiness.",
          "Carry a quick sugar source if your medicines can cause hypoglycemia.",
          "Foot, eye, kidney, and blood pressure checks prevent complications.",
          "Keep appointments even when you feel well; damage can be silent."]),
        ("evergreen-conditions-7", "Asthma control between flare-ups",
         "Preventers and triggers matter as much as rescue inhalers.",
         ["Asthma narrows airways and flares with smoke, dust, colds, or allergens.",
          "Take controller inhalers as prescribed even on good days if planned.",
          "Know preventer versus reliever inhalers and check your technique.",
          "Ask a clinician or pharmacist to watch you use your device.",
          "Seek urgent care for speaking only in short phrases or blue lips.",
          "A written action plan helps families respond consistently."]),
        ("evergreen-conditions-8", "Understanding anemia symptoms",
         "Low red blood cells leave you tired—but causes differ.",
         ["Anemia may come from iron lack, blood loss, malaria, or chronic disease.",
          "Fatigue, pale skin, breathlessness, and dizziness are clues, not a full diagnosis.",
          "Do not start high-dose iron without knowing the cause.",
          "Testing guides safer treatment and avoids harm from excess iron.",
          "Pregnancy, childhood growth, and heavy periods need special attention.",
          "Black stools, vomiting blood, or collapse are emergencies."]),
        ("evergreen-conditions-9", "Kidney health: what to watch for",
         "Kidneys filter waste—protect them by managing upstream risks.",
         ["High blood pressure and diabetes drive much chronic kidney disease.",
          "Control those conditions and avoid unnecessary long-term painkiller overuse.",
          "Foamy urine, swelling, or low urine output need follow-up.",
          "Lab creatinine changes may require medicine dose adjustments.",
          "Ask before herbal mixtures if you already have kidney disease.",
          "Early specialist referral can slow progression for many people."]),
        ("evergreen-conditions-10", "Arthritis pain without giving up movement",
         "Gentle activity often protects joints better than total rest.",
         ["Mix movement, strength, and paced rest for joint pain.",
          "Water exercise and short walks are often easier than sudden long runs.",
          "A healthier weight reduces load on knees and hips when achievable.",
          "Heat, ice, and clinician-guided pain plans can ease flares.",
          "Hot swollen joints with fever need prompt review.",
          "Sudden inability to bear weight can signal infection or injury."]),
    ],
}

# Remaining categories filled below in SAME structure via extend.
TOPICS["symptoms"] = [
    ("evergreen-symptoms-1", "Fever: what the number does not tell alone",
     "How you look and drink matters as much as the thermometer.",
     ["Fever is a body response, not always an emergency by itself.",
      "Note age, alertness, fluid intake, and other symptoms with the reading.",
      "Babies under three months with fever need urgent assessment.",
      "Seek care for stiff neck, rash with fever, confusion, or breathing trouble.",
      "Use age-appropriate fever medicine only as labeled.",
      "Never give aspirin to children unless a clinician specifically advises it."]),
    ("evergreen-symptoms-2", "Shortness of breath you should not ignore",
     "Breathing trouble can escalate quickly—know urgent patterns.",
     ["Sudden severe breathlessness needs emergency care.",
      "Breathing trouble with chest pain, blue lips, or confusion is urgent.",
      "Inability to speak full sentences is a danger sign.",
      "People with asthma, heart failure, or anemia may notice gradual change.",
      "Track whether stairs or walking distance suddenly worsen.",
      "Do not wait overnight if breathing is rapidly getting worse."]),
    ("evergreen-symptoms-3", "Headache red flags",
     "Most headaches settle—some patterns need same-day care.",
     ["Sudden worst headache of your life needs emergency assessment.",
      "Headache with fever and stiff neck is urgent.",
      "Weakness, vision loss, or speech trouble with headache is urgent.",
      "Head injury with worsening headache needs review.",
      "Track migraine patterns and triggers in a simple diary.",
      "Frequent painkiller use can itself worsen headaches over time."]),
    ("evergreen-symptoms-4", "Abdominal pain: mild versus urgent",
     "Location, fever, and vomiting guide how fast to act.",
     ["Mild cramps after rich meals often settle with rest and fluids.",
      "Severe pain that prevents walking needs prompt care.",
      "Pain with vomiting blood, black stools, or fainting is an emergency.",
      "Pregnancy plus abdominal pain needs urgent evaluation.",
      "Rigid abdomen or pain with high fever can signal serious infection.",
      "Do not ignore pain that migrates to the lower right abdomen."]),
    ("evergreen-symptoms-5", "Dizziness and fainting clues",
     "Brief lightheadedness differs from stroke-like symptoms.",
     ["Stand up slowly if you feel lightheaded after lying down.",
      "Drink fluids if heat or dehydration may be involved.",
      "Fainting with chest pain or irregular heartbeat needs urgent care.",
      "Sudden imbalance with facial droop or speech trouble suggests stroke pathways.",
      "Medicines for blood pressure can contribute to dizziness.",
      "Keep a list of episodes to share with your clinician."]),
    ("evergreen-symptoms-6", "Chest tightness that is not classic pain",
     "Pressure, burning, or heaviness can still be cardiac.",
     ["Describe tightness, burning, or heaviness clearly to responders.",
      "Symptoms with exertion that ease at rest still matter.",
      "Nausea, sweating, or jaw discomfort can accompany heart ischemia.",
      "Anxiety can cause chest symptoms, but do not self-diagnose in a crisis.",
      "When unsure, treat new severe chest symptoms as urgent.",
      "Known heart disease raises the threshold for seeking help early."]),
    ("evergreen-symptoms-7", "Persistent cough beyond a simple cold",
     "Duration and accompanying signs change the next step.",
     ["Cough lasting more than three weeks deserves clinical review.",
      "Coughing blood needs prompt assessment.",
      "Night sweats, weight loss, or fever with cough need evaluation.",
      "Asthma, reflux, and post-nasal drip are common contributors.",
      "Smoking history should always be shared with your clinician.",
      "Wheeze or breathlessness with cough may need inhaler review."]),
    ("evergreen-symptoms-8", "Urinary burning and frequency",
     "Bladder infections are common—complications still matter.",
     ["Burning, urgency, and frequent small voids suggest urinary infection.",
      "Drink fluids and seek care if symptoms persist or worsen.",
      "Fever, back pain, or vomiting can signal kidney involvement.",
      "Pregnancy plus urinary symptoms needs timely review.",
      "Men with urinary symptoms may need prostate-related assessment.",
      "Complete prescribed antibiotics when they are given."]),
    ("evergreen-symptoms-9", "Rash with fever or rapid spread",
     "Skin changes plus systemic signs raise urgency.",
     ["Fever with a new non-blanching rash needs urgent care.",
      "Rapidly spreading redness and pain can signal cellulitis.",
      "Blistering rashes after new medicines need prompt advice.",
      "Itchy hives with lip swelling or wheeze can be anaphylaxis.",
      "Photograph progressing rashes to show clinicians change over hours.",
      "Do not delay care while waiting for an outpatient slot if you feel very unwell."]),
    ("evergreen-symptoms-10", "Swelling in legs or sudden face puffiness",
     "Edema has many causes—some need same-day review.",
     ["One-sided leg swelling with pain can suggest clot risk.",
      "Breathlessness with leg swelling may involve heart strain.",
      "Sudden facial swelling with allergy signs is an emergency.",
      "Kidney and liver disease can cause progressive swelling.",
      "High salt intake and some medicines worsen fluid retention.",
      "Report rapid weight gain of several kilos over days."]),
    ("evergreen-symptoms-11", "Unusual fatigue that does not improve",
     "Tiredness is common—red flags still deserve labs and history.",
     ["Fatigue after short sleep often improves with rest and routine.",
      "Fatigue with weight loss, night sweats, or fevers needs review.",
      "Breathlessness, pale skin, or heavy periods may point to anemia.",
      "Thyroid, depression, and chronic infections are other considerations.",
      "List medicines and supplements when you seek assessment.",
      "Sudden collapse or confusion with fatigue needs emergency care."]),
    ("evergreen-symptoms-12", "Blood in stool or vomit",
     "Visible blood is a reason to seek care promptly.",
     ["Vomiting blood or coffee-ground material is an emergency.",
      "Black tarry stools can mean digested blood from higher in the gut.",
      "Bright red blood may be local, but still needs assessment.",
      "Dizziness or fainting with bleeding raises urgency further.",
      "Do not take more anti-inflammatories if they may be irritating the stomach.",
      "Bring a medicine list including over-the-counter pain pills."]),
    ("evergreen-symptoms-13", "Confusion or sudden behavior change",
     "New confusion is a medical urgent sign at any age.",
     ["Sudden confusion can come from infection, low sugar, stroke, or medicines.",
      "Older adults may show urinary infection as confusion rather than fever alone.",
      "Check for trauma, missed medicines, or alcohol withdrawal context.",
      "Face droop, arm weakness, or speech trouble suggest stroke pathways.",
      "Keep the person safe from falls while you seek emergency help.",
      "Bring the medication list to the hospital or clinic."]),
    ("evergreen-symptoms-14", "Eye pain, sudden vision change, or chemical splash",
     "Eyes need fast action for some problems.",
     ["Sudden vision loss is an emergency until proven otherwise.",
      "Eye pain with nausea or halos can signal acute pressure problems.",
      "Chemical splashes need immediate prolonged water rinsing, then care.",
      "New floaters with flashes deserve prompt ophthalmology review.",
      "Contact lens pain with redness can mean serious infection.",
      "Do not delay because you hope blur will clear overnight."]),
    ("evergreen-symptoms-15", "Allergic reactions: mild versus emergency",
     "Know when antihistamines are not enough.",
     ["Mild itchy hives without breathing trouble may settle with advice and antihistamines.",
      "Lip, tongue, or throat swelling is an emergency.",
      "Wheeze, trouble breathing, or collapse means call emergency services.",
      "If you carry epinephrine, use it as trained for anaphylaxis.",
      "Avoid the suspected trigger and seek follow-up allergy guidance.",
      "Document reactions so future clinicians see the pattern quickly."]),
]

TOPICS["family"] = [
    ("evergreen-child-1", "When a child’s fever needs attention",
     "Age, how the child looks, and other symptoms matter as much as the number.",
     ["Fever is a response to infection; older alert children may need monitoring and fluids.",
      "Babies under three months with fever need urgent care.",
      "Seek help if a child is very sleepy, hard to wake, or has a stiff neck.",
      "Rash with fever, breathing trouble, seizures, or persistent vomiting are urgent.",
      "Use age-appropriate fever medicine only as directed on the label.",
      "Never give aspirin to children unless a clinician specifically advises it."]),
    ("evergreen-child-2", "Hydration and oral rehydration for kids",
     "Fluids matter most with diarrhea, vomiting, or hot-weather illness.",
     ["Offer small frequent sips rather than large amounts if nausea is present.",
      "Use clean water or oral rehydration solution as advised.",
      "Watch for dry mouth, fewer wet diapers, sunken eyes, or unusual lethargy.",
      "Continue breastfeeding if that is the baby’s usual feeding.",
      "Avoid sugary sodas and undiluted juice as the main fluid during illness.",
      "Seek care when dehydration signs appear or vomiting prevents all fluids."]),
    ("evergreen-child-3", "Vaccines for children on schedule",
     "Timely immunization prevents many serious childhood infections.",
     ["Follow the national schedule discussed at clinic visits.",
      "Bring the vaccine card to every visit to catch missed doses.",
      "Mild fever or soreness after shots is common and usually short-lived.",
      "Ask which vaccines are due before school entry or travel.",
      "Children with special health conditions may need extra doses.",
      "Never skip vaccines because a child looks healthy today."]),
    ("evergreen-child-4", "Safe sleep for babies",
     "Simple sleep setup lowers sudden infant death risk.",
     ["Place babies on their back to sleep on a firm flat surface.",
      "Keep soft bedding, pillows, and loose blankets out of the sleep space.",
      "Share a room when recommended, but avoid soft shared sleep surfaces.",
      "Avoid smoke exposure around infants.",
      "Dress babies for the room temperature without overheating.",
      "Ask your clinician about safe sleep if you have twins or preterm babies."]),
    ("evergreen-child-5", "Nutrition building blocks for growing kids",
     "Variety and regular meals support growth better than perfection.",
     ["Offer fruits, vegetables, proteins, and energy foods across the week.",
      "Limit sugary drinks; prefer water and milk as age-appropriate.",
      "Eat together when possible so children learn calm meal routines.",
      "Watch for poor weight gain, extreme pickiness with fatigue, or frequent illness.",
      "Ask about vitamin or mineral needs based on local guidance.",
      "Avoid forcing finishes; repeated gentle exposure helps acceptance."]),
    ("evergreen-pregnancy-1", "Early pregnancy warning signs",
     "Some symptoms need same-day care even in early weeks.",
     ["Heavy bleeding, severe one-sided pain, or fainting need urgent care.",
      "Severe vomiting that prevents fluids needs review.",
      "Fever in pregnancy should not be ignored.",
      "Start prenatal visits as soon as pregnancy is known when possible.",
      "Share all medicines and herbal products at the first visit.",
      "Know the nearest facility that can assess pregnancy emergencies."]),
    ("evergreen-pregnancy-2", "Nutrition and supplements in pregnancy",
     "Balanced eating plus recommended supplements support mother and baby.",
     ["Take folic acid as advised before and in early pregnancy when possible.",
      "Eat iron-rich foods and ask about iron supplements if prescribed.",
      "Stay hydrated and limit excess caffeine according to local guidance.",
      "Avoid alcohol in pregnancy.",
      "Food safety matters: thoroughly cooked meats and safe water help.",
      "Discuss any special diet with your clinician so gaps are covered."]),
    ("evergreen-pregnancy-3", "Movement and rest while pregnant",
     "Gentle activity helps many pregnancies when clinicians agree it is safe.",
     ["Walking and prenatal-appropriate exercise often support mood and sleep.",
      "Avoid contact sports and activities with high fall risk unless cleared.",
      "Rest with legs elevated if swelling bothers you and advice allows.",
      "Stop activity for bleeding, severe dizziness, or regular painful contractions.",
      "Sleep on the side later in pregnancy if recommended for you.",
      "Ask before starting a new intense fitness program while pregnant."]),
    ("evergreen-pregnancy-4", "Danger signs in later pregnancy",
     "Headache, vision change, and reduced baby movements matter.",
     ["Severe headache, vision spots, or sudden hand and face swelling need urgent care.",
      "Reduced fetal movements should be assessed promptly.",
      "Vaginal bleeding or fluid leaking before labor needs review.",
      "Regular painful contractions before term need assessment.",
      "Fever or burning urination can still be serious in pregnancy.",
      "Keep emergency transport plans ready in the third trimester."]),
    ("evergreen-pregnancy-5", "Postpartum recovery and mental health",
     "Healing after birth includes body and mood support.",
     ["Heavy bleeding soaking pads hourly needs urgent care.",
      "Fever, wound redness, or foul discharge need review.",
      "Baby blues are common; ongoing low mood or scary thoughts need help.",
      "Sleep when the baby sleeps when you can, and accept practical support.",
      "Ask about contraception timing that fits feeding plans.",
      "Attend postpartum checks even if you feel mostly fine."]),
    ("evergreen-family-6", "Caring for older adults at home",
     "Mobility, medicines, and social contact shape healthy aging.",
     ["Reduce trip hazards and improve lighting to prevent falls.",
      "Review medicine lists regularly for duplicates and side effects.",
      "Encourage walking and strength within ability and clinical advice.",
      "Watch for confusion that may signal infection or medicine effects.",
      "Support hearing and vision checks that preserve independence.",
      "Loneliness affects health—plan regular contact and community links."]),
    ("evergreen-family-7", "Family emergency plans that work",
     "A written plan helps when someone suddenly falls ill.",
     ["List local emergency numbers and nearest open facilities.",
      "Keep allergy and medicine lists for each household member.",
      "Agree who carries phones and transport money at night.",
      "Practice how children call for help and share an address.",
      "Store a small first-aid kit where everyone can find it.",
      "Update the plan after moves, new diagnoses, or new babies."]),
    ("evergreen-family-8", "Supporting a household member with chronic illness",
     "Practical help beats advice alone.",
     ["Offer rides to appointments and help organize medicine schedules.",
      "Learn warning signs specific to their condition with their consent.",
      "Share cooking and shopping that fits dietary guidance.",
      "Avoid shaming setbacks; celebrate small consistent habits.",
      "Caregivers need rest too—ask relatives or community groups for relief.",
      "Join clinic education sessions when invited."]),
    ("evergreen-family-9", "Adolescent health conversations at home",
     "Respectful talk about bodies, consent, and mental load matters.",
     ["Create private calm moments for questions without lectures.",
      "Discuss consent, contraception, and infection prevention honestly.",
      "Watch for withdrawal, sleep collapse, or talk of self-harm.",
      "Support school and sport balance rather than perfection pressure.",
      "Confidential clinic services may help teens ask what they cannot ask at home.",
      "Model healthy phone and sleep habits as adults."]),
    ("evergreen-family-10", "Breastfeeding and infant feeding support",
     "Feeding choices deserve skilled support, not judgment.",
     ["Skin-to-skin and early feeding help many breastfeeding starts.",
      "Painful cracked nipples or poor weight gain need lactation or clinic help.",
      "Exclusive breastfeeding guidance varies by context—follow local clinical advice.",
      "If using formula, prepare feeds with safe water and clean bottles.",
      "Watch wet diapers and alertness as feeding adequacy clues.",
      "Ask for help early rather than struggling alone for weeks."]),
]


def expand(points: list[str]) -> str:
    """Turn teaching points into multi-paragraph prose with disclaimer."""
    chunks: list[str] = []
    # Group points into ~3 paragraphs
    for i in range(0, len(points), 2):
        pair = points[i : i + 2]
        chunks.append(" ".join(pair))
    body = "\n\n".join(chunks)
    body = f"{body}\n\n{DISCLAIMER}"
    # Guarantee ≥100 words with a stable educational closer if needed
    while word_count(body) < 100:
        body += (
            " Write down questions before clinic visits, bring your medicine list, "
            "and share how symptoms change across days so clinicians can advise more accurately."
        )
    return body


def word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def build_article(item: tuple[str, str, str, list[str]]) -> dict:
    id_, title, summary, points = item
    content = expand(points)
    assert word_count(content) >= 100, f"{id_}: {word_count(content)}"
    return {"id": id_, "title": title, "summary": summary, "content": content}


# Continue remaining categories
TOPICS["emergency"] = [
    ("evergreen-emergency-1", "Call for help: what to say clearly",
     "Clear information speeds the right response.",
     ["State your exact location and the main problem in one sentence.",
      "Share the person’s age range, consciousness, and breathing status.",
      "Do not hang up until the dispatcher says you may.",
      "Put the phone on speaker if you must give first aid.",
      "Send someone to guide responders if it is safe.",
      "Keep the scene as calm and lighted as you can."]),
    ("evergreen-emergency-2", "Choking: back blows and when to act",
     "A silent choking person needs immediate help.",
     ["If someone cannot cough, speak, or breathe, act at once.",
      "Call for emergency help while starting first aid if others are present.",
      "Use age-appropriate back blows and abdominal thrusts if trained.",
      "Infants need different techniques than adults—learn them before a crisis.",
      "Continue until the object clears or the person becomes unresponsive.",
      "Even after success, seek review if breathing remains noisy or painful."]),
    ("evergreen-emergency-3", "Severe bleeding control",
     "Pressure and elevation save time before professionals arrive.",
     ["Apply firm direct pressure with a clean cloth on the wound.",
      "Add more cloth without removing the first layer if it soaks through.",
      "Elevate the limb if it does not worsen pain from a fracture concern.",
      "Use a tourniquet only if trained and bleeding is life-threatening on a limb.",
      "Do not remove embedded objects; stabilize them and get help.",
      "Watch for shock: pale skin, rapid pulse, confusion, or fainting."]),
    ("evergreen-emergency-4", "Stroke signs: act fast",
     "Face, Arm, Speech, Time remains a useful memory aid.",
     ["Sudden face droop, arm weakness, or speech trouble needs emergency care.",
      "Note the time symptoms started for clinicians.",
      "Do not give food, drink, or aspirin unless told by professionals.",
      "Keep the person sitting or lying safely while waiting.",
      "Sudden severe imbalance or vision loss can also be stroke-related.",
      "Faster arrival improves treatment options in many settings."]),
    ("evergreen-emergency-5", "Seizure first aid without panic",
     "Protect the person; do not force objects into the mouth.",
     ["Ease the person to the ground and clear sharp objects nearby.",
      "Cushion the head and turn them on their side when possible.",
      "Do not restrain movements or put fingers in the mouth.",
      "Time the seizure; call emergency help if it lasts over five minutes.",
      "Call help sooner for first seizures, pregnancy, or repeated seizures.",
      "Stay until they are fully awake and oriented."]),
    ("evergreen-emergency-6", "Burns: cool water first",
     "Cooling quickly reduces damage; some burns need hospital care.",
     ["Cool the burn under clean running water for about twenty minutes.",
      "Remove tight items near the area before swelling increases.",
      "Do not apply butter, toothpaste, or traditional pastes.",
      "Cover loosely with clean non-fluffy material afterward.",
      "Seek care for burns on face, hands, joints, or genitals.",
      "Large, deep, or chemical and electrical burns need emergency care."]),
    ("evergreen-emergency-7", "Suspected heart attack response",
     "Fast recognition and rest while help comes matter.",
     ["Call emergency services for pressure-like chest pain with warning signs.",
      "Have the person rest sitting or lying comfortably.",
      "Loosen tight clothing and keep the space calm.",
      "If local protocols advise aspirin and the person is not allergic, follow dispatcher guidance.",
      "Do not leave them alone if you can stay safely.",
      "Be ready to describe medicines and allergies to responders."]),
    ("evergreen-emergency-8", "Poisoning and overdose basics",
     "Bring containers; do not force vomiting unless told.",
     ["Call emergency or poison guidance with the product name if known.",
      "Do not induce vomiting unless a professional instructs you.",
      "Move the person to fresh air for inhaled fumes if safe for you.",
      "Rinse skin or eyes with water for chemical contact.",
      "Keep the person awake and breathing while waiting when possible.",
      "Take the medicine bottle or packaging to the facility."]),
    ("evergreen-emergency-9", "Fractures and sprains until help arrives",
     "Immobilize and avoid unnecessary movement.",
     ["Support the injured limb in the position found if moving hurts.",
      "Ice wrapped in cloth can ease swelling for many sprains.",
      "Do not try to realign a deformed bone yourself.",
      "Open fractures with bone visible need sterile cover and urgent care.",
      "Watch fingers or toes for color and sensation changes.",
      "Seek care for inability to bear weight or numbness."]),
    ("evergreen-emergency-10", "Allergic emergency and epinephrine",
     "Anaphylaxis can progress in minutes.",
     ["Lip, tongue, or throat swelling with breathing trouble is an emergency.",
      "Use prescribed epinephrine as trained, then call emergency services.",
      "Lay the person flat unless breathing is easier sitting upright.",
      "Avoid the suspected trigger and note what was eaten or injected.",
      "A second dose may be advised if symptoms persist—follow training.",
      "Everyone with prior anaphylaxis should have an action plan."]),
    ("evergreen-emergency-11", "Heat stroke versus heat exhaustion",
     "Confusion and very high temperature need emergency cooling help.",
     ["Move the person to shade and loosen clothing.",
      "Cool with water and fanning while awaiting help for severe cases.",
      "Heat stroke can include confusion, seizures, or hot dry skin.",
      "Offer sips of water only if the person is fully awake.",
      "Workers and athletes in humid heat are at special risk.",
      "Do not leave someone alone if mental status is altered."]),
    ("evergreen-emergency-12", "Drowning response and water safety",
     "Seconds matter; do not become a second victim.",
     ["Call for help and reach with a stick or throw a float if possible.",
      "Enter water to rescue only if you are trained and it is safe.",
      "Start CPR if trained when the person is unresponsive and not breathing normally.",
      "Even after recovery, hospital review is important.",
      "Supervise children closely around buckets, baths, and open water.",
      "Barriers and swim skills reduce risk but never replace supervision."]),
    ("evergreen-emergency-13", "Snakebite first steps",
     "Keep still, seek care, avoid harmful traditional cuts.",
     ["Move away from the snake and keep the person as still as possible.",
      "Remove rings and tight items near the bite before swelling.",
      "Do not cut, suck, or apply ice as routine first aid.",
      "Do not use tight tourniquets unless local expert guidance says otherwise.",
      "Get to a facility that can assess antivenom need.",
      "Photograph the snake only if it is safe and distant—do not hunt it."]),
    ("evergreen-emergency-14", "Electric shock safety",
     "Turn off power before touching the person if you can.",
     ["Shut off the source or disconnect power before contact when possible.",
      "Do not touch someone still in contact with live electricity.",
      "Call emergency services for any significant shock.",
      "Check breathing and start CPR if trained and needed.",
      "Burns may look small on the surface yet be deeper.",
      "Fall injuries after shock also need assessment."]),
    ("evergreen-emergency-15", "Road crash first actions",
     "Scene safety comes before first aid.",
     ["Ensure oncoming traffic will not hit you or the injured.",
      "Call emergency services with location and number of injured people.",
      "Turn off vehicle ignition if safe and accessible.",
      "Avoid moving people with possible spine injuries unless immediate danger.",
      "Control severe bleeding with pressure while waiting.",
      "Stay until professionals arrive unless the scene becomes unsafe."]),
]

TOPICS["care_system"] = [
    ("evergreen-care-1", "How to prepare for a clinic visit",
     "A short plan helps you leave with clearer next steps.",
     ["Write your top three concerns before you arrive.",
      "Bring all medicines and supplements in their packages if possible.",
      "Note symptom start dates and what makes them better or worse.",
      "Ask who to call if results need follow-up.",
      "Confirm the cost or insurance steps before procedures when you can.",
      "Leave with written instructions for medicines and return timing."]),
    ("evergreen-care-2", "Choosing urgent care versus emergency departments",
     "Match the facility to how dangerous symptoms look.",
     ["Emergency departments handle life-threatening problems day and night.",
      "Urgent care suits many fevers, sprains, and infections when stable.",
      "Chest pain, stroke signs, severe breathing trouble, and major trauma need emergency pathways.",
      "If unsure and symptoms escalate, choose the higher level of care.",
      "Know which nearby facilities are open overnight.",
      "Bring ID, payment method, and medicine lists to either setting."]),
    ("evergreen-care-3", "Understanding referrals and specialists",
     "Referrals connect primary care with deeper expertise.",
     ["Ask why a referral is recommended and how soon to go.",
      "Confirm whether you need test results before the specialist visit.",
      "Bring prior notes and imaging reports if you have copies.",
      "Ask how information will return to your primary clinician.",
      "If wait times are long, ask about interim warning signs.",
      "Keep a folder or phone album of key reports."]),
    ("evergreen-care-4", "Reading a basic prescription label",
     "Dose, timing, and duration prevent common medicine mistakes.",
     ["Check the medicine name against what the clinician said.",
      "Note how many times daily and whether to take with food.",
      "Clarify what to do if you miss a dose.",
      "Ask how long the course lasts, especially for antibiotics.",
      "Store as labeled—some medicines need cool dry places.",
      "Never share prescription medicines with others."]),
    ("evergreen-care-5", "Consent and asking questions without fear",
     "You can request plain-language explanations before procedures.",
     ["Ask about benefits, risks, and alternatives in words you understand.",
      "Request an interpreter if language is a barrier.",
      "You may pause to think or involve a trusted person when appropriate.",
      "Emergency care can proceed to save life when consent is impossible.",
      "Write answers down or ask staff to write key points.",
      "Respectful questions improve safety for everyone."]),
    ("evergreen-care-6", "Keeping a personal health summary",
     "A one-page summary helps new clinicians treat you safely.",
     ["List conditions, surgeries, allergies, and regular medicines.",
      "Include emergency contacts and your preferred hospital if any.",
      "Note vaccines and major test dates when known.",
      "Update after each significant clinic change.",
      "Store a photo of the page on your phone offline.",
      "Share it during emergencies when you cannot speak well."]),
    ("evergreen-care-7", "Navigating lab results follow-up",
     "Results only help if someone reviews and explains them.",
     ["Ask when and how results will be shared.",
      "Do not assume no news means normal without confirmation.",
      "Request a call or visit for abnormal values that need action.",
      "Bring printed or electronic copies to the next appointment.",
      "Ask which numbers matter most for your condition.",
      "Clarify lifestyle or medicine changes tied to the results."]),
    ("evergreen-care-8", "Insurance, cash, and asking about costs",
     "Cost questions are legitimate parts of care planning.",
     ["Ask for estimates before non-emergency procedures when possible.",
      "Clarify what is included: consult, tests, medicines, follow-up.",
      "Request generic medicine options if clinically appropriate.",
      "Ask about payment plans or social support desks.",
      "Keep receipts for reimbursement if your plan allows.",
      "Emergency care should not be delayed solely for payment talks—stabilize first."]),
    ("evergreen-care-9", "Telehealth visits that actually help",
     "Remote care works best with preparation and clear limits.",
     ["Test your connection and sit in a quiet private space.",
      "Have medicines and a symptom timeline ready to show on camera.",
      "Describe severity and duration precisely.",
      "Ask when in-person care is still required.",
      "Confirm how prescriptions will be sent to a pharmacy.",
      "Seek emergency care for red-flag symptoms instead of waiting on a call."]),
    ("evergreen-care-10", "Hospital discharge: leaving safely",
     "The day you leave is a high-risk transition.",
     ["Review new medicines against old ones before you go.",
      "Know warning signs that mean return urgently.",
      "Confirm follow-up appointments and who to call with questions.",
      "Understand wound care, diet, and activity limits.",
      "Arrange transport and home support if mobility is limited.",
      "Keep discharge papers with your health summary."]),
    ("evergreen-care-11", "Finding trustworthy health information",
     "Not every viral tip is safe or relevant to you.",
     ["Prefer clinic handouts and recognized public health sites.",
      "Be cautious with miracle cures and unverified herbal claims.",
      "Check dates—guidance changes as evidence grows.",
      "Discuss online findings with a clinician before acting.",
      "Watch for scams asking for payment for free public advice.",
      "CareMate Learn articles are educational starting points, not prescriptions."]),
    ("evergreen-care-12", "Second opinions without burning bridges",
     "Complex decisions can benefit from another clinical view.",
     ["Ask politely for your records to share with another clinician.",
      "Second opinions are common for surgery and cancer pathways.",
      "Bring organized copies rather than fragmented messages.",
      "Explain you want clarity, not conflict.",
      "Compare recommendations and ask questions about differences.",
      "Choose the plan you understand and can follow safely."]),
    ("evergreen-care-13", "Pharmacy counseling you should request",
     "Pharmacists catch interactions and timing issues.",
     ["Ask whether new medicines interact with what you already take.",
      "Confirm if alcohol, driving, or food restrictions apply.",
      "Clarify measuring tools for liquid medicines.",
      "Ask about common side effects and which ones need a call.",
      "Check the name on the bag before leaving the counter.",
      "Return if labeling looks different from what you expected."]),
    ("evergreen-care-14", "Community health workers and local clinics",
     "Primary care networks extend beyond hospitals.",
     ["Community clinics handle many vaccinations and chronic disease checks.",
      "Community health workers can help with education and follow-up.",
      "Ask which services need appointments versus walk-in hours.",
      "Bring identity documents required for registration if any.",
      "Use local services for prevention so hospitals stay free for crises.",
      "Feedback helps clinics improve waiting and communication."]),
    ("evergreen-care-15", "Patient rights and respectful care",
     "Dignity and privacy are part of quality healthcare.",
     ["You can expect privacy during examinations as much as the setting allows.",
      "Ask who is in the room and why.",
      "You may request same-gender clinicians when available for sensitive exams.",
      "Discrimination should be reported through facility channels.",
      "Clear consent matters for procedures and student involvement.",
      "Respectful partnerships improve adherence and outcomes."]),
]

TOPICS["medicines"] = [
    ("evergreen-medication-1", "How to take medicines safely",
     "Timing, food, and completing courses prevent many problems.",
     ["Take medicines exactly as labeled unless a clinician changes the plan.",
      "Ask whether doses should be with food, water, or an empty stomach.",
      "Use reminders so busy days do not cause skipped doses.",
      "Do not double doses after a miss unless instructed.",
      "Finish antibiotic courses as directed even if you feel better.",
      "Tell clinicians about all herbs and over-the-counter products."]),
    ("evergreen-medication-2", "Storing medicines at home",
     "Heat, humidity, and curious children create avoidable risks.",
     ["Store most medicines in a cool dry place away from sunlight.",
      "Keep medicines locked away from children and pets.",
      "Do not store tablets in steamy bathrooms if labels warn against moisture.",
      "Check expiry dates during seasonal clean-ups.",
      "Ask a pharmacist how to dispose of unused opioids or antibiotics.",
      "Keep medicines in original labeled containers when possible."]),
    ("evergreen-medication-3", "Side effects versus allergies",
     "Knowing the difference guides how urgently you respond.",
     ["Nausea or mild stomach upset can be side effects—ask if they will settle.",
      "Rash, swelling, or breathing trouble can signal allergy or anaphylaxis.",
      "Stop the medicine and seek urgent care for severe allergic signs.",
      "Report side effects that disrupt sleep, mood, or daily function.",
      "Do not restart a medicine that caused a serious reaction without advice.",
      "Carry allergy information on your phone and health summary."]),
    ("evergreen-medication-4", "Pain medicines: use with care",
     "Common painkillers still have dose limits and interaction risks.",
     ["Follow package maximum doses for paracetamol and anti-inflammatories.",
      "Liver disease changes safe paracetamol limits—ask first.",
      "Stomach ulcers, kidney disease, and some heart conditions limit anti-inflammatories.",
      "Avoid mixing multiple products that contain the same ingredient.",
      "Long-term daily painkiller use needs clinical review.",
      "Seek help for overdose suspicions immediately."]),
    ("evergreen-medication-5", "Antibiotics: when they help",
     "Antibiotics treat bacterial infections, not most viral colds.",
     ["They will not shorten most uncomplicated colds or flu-like viruses.",
      "Unnecessary use drives resistance and side effects.",
      "Take the full prescribed course at evenly spaced times.",
      "Do not share leftover antibiotics with family members.",
      "Ask why an antibiotic is chosen and what infection it targets.",
      "Report severe diarrhea while on antibiotics promptly."]),
    ("evergreen-medicines-6", "Using inhalers the right way",
     "Technique often matters more than brand differences.",
     ["Shake and prime devices as instructed for your inhaler type.",
      "Breathe out first, seal lips, inhale steadily, then hold briefly if advised.",
      "Spacers help many people get more medicine into the lungs.",
      "Rinse the mouth after steroid inhalers when recommended.",
      "Track how often you need reliever doses—frequent use needs review.",
      "Ask a pharmacist to watch your technique yearly."]),
    ("evergreen-medicines-7", "Insulin and diabetes supplies basics",
     "Safe storage and rotation protect glucose control.",
     ["Store unopened insulin as labeled, often refrigerated.",
      "Do not freeze insulin or leave pens in hot cars.",
      "Rotate injection sites to reduce skin lumps.",
      "Never share needles or pens.",
      "Carry quick sugar and know low-glucose symptoms.",
      "Ask how to adjust doses during illness only under clinical guidance."]),
    ("evergreen-medicines-8", "Blood pressure pills: sticking with the plan",
     "Feeling fine does not mean hypertension is gone.",
     ["Take tablets at the same time daily for steadier control.",
      "Refill before the pack ends to avoid gaps.",
      "Dizziness after starting or increasing doses deserves a call.",
      "Do not stop suddenly without advice—some medicines need tapering.",
      "Home readings help clinicians fine-tune therapy.",
      "Share all other medicines that might raise blood pressure."]),
    ("evergreen-medicines-9", "Traveling with medicines",
     "Packing and documentation prevent border and heat problems.",
     ["Carry medicines in hand luggage with original labels.",
      "Bring extra days of supply for delays.",
      "Ask for a clinician letter for syringes or controlled medicines if needed.",
      "Keep temperature-sensitive products in recommended cool packs.",
      "Know local brand names or generic names at your destination.",
      "Set phone reminders for time-zone dose shifts."]),
    ("evergreen-medicines-10", "Herbals and supplements still interact",
     "Natural does not mean risk-free with prescription drugs.",
     ["Tell clinicians about every herbal tea, powder, and capsule.",
      "Some products affect bleeding risk or liver enzymes.",
      "Pregnancy and kidney disease change what is safe.",
      "Avoid megadoses unless prescribed and monitored.",
      "Buy from reputable sources to reduce contamination risk.",
      "Stop products before surgery when your surgical team advises."]),
    ("evergreen-medicines-11", "Liquid medicines and measuring tools",
     "Kitchen spoons are inaccurate for doses.",
     ["Use the syringe or cup that comes with the medicine.",
      "Ask for a demonstration if markings are unclear.",
      "Shake suspensions when labels say so.",
      "Refrigerate only if the label requires it.",
      "Write the child’s weight-based dose plan from the clinician.",
      "Do not guess leftover amounts after spills—ask for advice."]),
    ("evergreen-medicines-12", "Eye and ear drops without contamination",
     "Clean technique protects sensitive tissues.",
     ["Wash hands before applying drops.",
      "Avoid touching the dropper tip to eye, ear, or skin.",
      "Wait between different drop medicines as instructed.",
      "Discard bottles by the labeled beyond-use date after opening.",
      "Stop and seek care if pain, vision change, or discharge worsens.",
      "Store caps clean and replace them promptly."]),
    ("evergreen-medicines-13", "Mental health medicines: patience and monitoring",
     "Benefits often build over weeks; side effects need reporting.",
     ["Antidepressants and related medicines may take time to help.",
      "Do not stop suddenly without a taper plan when required.",
      "Report worsening mood, agitation, or unusual behavior promptly.",
      "Alcohol can worsen sedation and judgment on some medicines.",
      "Keep follow-up visits even when you start feeling better.",
      "Share pregnancy plans so regimens can be reviewed safely."]),
    ("evergreen-medicines-14", "Cold and cough remedies: read the label",
     "Multi-ingredient products can overlap accidentally.",
     ["Check whether a cold remedy already contains paracetamol.",
      "Sedating antihistamines affect driving and work safety.",
      "Children need age-specific products—not adult leftovers.",
      "Honey is not for infants under one year.",
      "Seek care when cough comes with breathing trouble or high fever.",
      "Ask a pharmacist to compare options with your other medicines."]),
    ("evergreen-medicines-15", "What to do after a missed dose",
     "The safe answer depends on the medicine type.",
     ["Check the leaflet or ask a pharmacist for that specific drug.",
      "Many once-daily medicines can be taken when remembered if far from the next dose.",
      "Do not double up automatically.",
      "Missed contraceptive or insulin doses need product-specific guidance.",
      "Set better reminders after a miss rather than guessing repeatedly.",
      "Bring a list of frequent misses to your next clinic visit."]),
]

TOPICS["mental"] = [
    ("evergreen-mental-1", "Spotting burnout before it peaks",
     "Exhaustion, cynicism, and reduced efficacy are warning patterns.",
     ["Burnout often mixes deep tiredness with detachment from work or study.",
      "Sleep debt, endless overtime, and lack of recovery days accelerate it.",
      "Small boundaries—protected breaks and realistic to-do lists—help early.",
      "Talk with a trusted person or manager about workload when safe.",
      "Persistent hopelessness deserves professional mental health support.",
      "Physical checkups can rule out contributors like anemia or thyroid issues."]),
    ("evergreen-mental-2", "Grounding techniques for anxious moments",
     "Simple sensory tools can lower intensity while you seek longer help.",
     ["Name five things you see, four you feel, three you hear, two you smell, one you taste.",
      "Slow exhales longer than inhales can reduce panic intensity.",
      "Plant your feet and notice solid contact with the floor.",
      "These tools complement—not replace—therapy or medicines when needed.",
      "Seek urgent help for chest pain with anxiety until cardiac causes are considered.",
      "Practice grounding on calm days so it is familiar in storms."]),
    ("evergreen-mental-3", "Sleep and mood travel together",
     "Protecting sleep is a core mental health habit.",
     ["Irregular sleep worsens irritability, focus, and worry.",
      "Keep a wind-down routine and consistent wake time when possible.",
      "Limit late caffeine and alcohol that fragment rest.",
      "If racing thoughts block sleep, write a short next-day list earlier in the evening.",
      "Chronic insomnia deserves clinical review.",
      "Sudden severe mood change with sleeplessness needs prompt assessment."]),
    ("evergreen-mental-4", "Talking with someone you trust",
     "Connection reduces isolation that fuels distress.",
     ["Choose a person who listens without immediate judgment.",
      "Use specific examples: sleep, appetite, concentration, and hope levels.",
      "Ask for practical help such as a clinic companion if useful.",
      "You do not owe anyone every detail to deserve support.",
      "If friends cannot help enough, professional counseling is appropriate.",
      "Helplines exist in many regions for acute despair—use them."]),
    ("evergreen-mental-5", "When low mood needs clinical care",
     "Duration, function loss, and safety concerns raise urgency.",
     ["Two weeks of low mood with lost interest deserves assessment.",
      "Inability to work, study, or care for children are important signals.",
      "Thoughts of self-harm require urgent professional help now.",
      "Depression is a medical condition, not a character failure.",
      "Therapy, medicines, or both may be recommended.",
      "Follow-up visits matter as much as the first prescription."]),
    ("evergreen-mental-6", "Panic attacks versus medical emergencies",
     "Panic feels terrifying—some symptoms still need emergency exclusion.",
     ["Panic often peaks within minutes with fear of dying or losing control.",
      "New chest pain or one-sided weakness still warrants emergency pathways.",
      "Once medical causes are addressed, panic-focused therapy helps many people.",
      "Breathing into a bag is outdated advice for most situations.",
      "Avoid excess caffeine if it triggers attacks.",
      "Track triggers to discuss with a clinician."]),
    ("evergreen-mental-7", "Social media and comparison fatigue",
     "Feeds can distort reality and sleep.",
     ["Curated highlight reels are not full lives.",
      "Set app time limits if scrolling worsens mood.",
      "Avoid screens in the last hour before bed when possible.",
      "Mute accounts that consistently leave you ashamed or angry.",
      "Replace some scroll time with outdoor light or real conversation.",
      "Seek help if online harassment leads to despair or fear."]),
    ("evergreen-mental-8", "Supporting a friend in crisis",
     "Listen, stay, and connect them to help.",
     ["Ask directly about safety if you worry about suicide—asking does not plant the idea.",
      "Stay with them while you contact emergency or crisis services if needed.",
      "Remove immediate means of harm when it is safe to do so.",
      "Avoid promises of total secrecy when life is at risk.",
      "Offer to help book appointments or attend the first visit.",
      "Care for your own stress after supporting someone in crisis."]),
    ("evergreen-mental-9", "Grief that needs extra support",
     "Mourning is natural; stuck overwhelming grief can be treated.",
     ["Wave-like sadness after loss is common.",
      "Seek help if you cannot function for weeks or feel permanently numb.",
      "Anniversary dates often intensify feelings—plan gentle support.",
      "Children grieve differently; keep routines and honest age-fit explanations.",
      "Cultural mourning practices can coexist with clinical care.",
      "Complicated grief therapy exists when pain remains disabling."]),
    ("evergreen-mental-10", "Workplace stress boundaries",
     "Sustainable performance needs recovery.",
     ["Define end-of-day shut-down rituals for messages when possible.",
      "Take real meal breaks away from screens.",
      "Use leave days instead of banking burnout.",
      "Document workload facts for constructive talks with supervisors.",
      "Peer support groups at work help some teams.",
      "Persistent bullying or unsafe pressure deserves formal reporting channels."]),
    ("evergreen-mental-11", "Breathing and body tension release",
     "Physical tension feeds mental tension.",
     ["Try slow box breathing: inhale, hold, exhale, hold in equal counts.",
      "Unclench jaw and drop shoulders several times a day.",
      "Short stretching breaks reduce accumulated stress signals.",
      "Warm showers or walks can interrupt rumination loops.",
      "Combine body tools with counseling when distress is ongoing.",
      "Stop any technique that causes dizziness or distress and seek guidance."]),
    ("evergreen-mental-12", "Parenting stress and asking for relief",
     "Caregiver overwhelm is common and solvable with support.",
     ["Sleep disruption with infants strains patience and mood.",
      "Ask relatives or friends for concrete help: meals, laundry, watching the child.",
      "Postpartum mood disorders need clinical care, not tougher willpower.",
      "Partner check-ins about workload prevent silent resentment.",
      "Community parenting groups reduce isolation.",
      "If you fear harming your child or yourself, seek emergency help immediately."]),
    ("evergreen-mental-13", "Focus problems and when to assess further",
     "Attention struggles have many causes across ages.",
     ["Sleep loss, depression, and anxiety commonly hurt focus.",
      "Sudden concentration collapse with other neurologic signs needs urgent care.",
      "School or work accommodations may help while assessment proceeds.",
      "Limit multitasking myths; single-task blocks often work better.",
      "Discuss concerns with a clinician rather than self-starting stimulants.",
      "Bring examples from home and work to the evaluation."]),
    ("evergreen-mental-14", "Substance use and mental health loops",
     "Alcohol and drugs can mask and worsen anxiety or depression.",
     ["Short-term relief from substances often deepens long-term symptoms.",
      "Withdrawal can cause anxiety, insomnia, and low mood.",
      "Be honest with clinicians—confidentiality rules usually protect care quality.",
      "Cutting down plans work better with support than willpower alone.",
      "Emergency care is needed for overdose, seizures, or suicidal crisis.",
      "Recovery communities and counseling both have roles."]),
    ("evergreen-mental-15", "Building a personal wellbeing toolkit",
     "Stack small reliable habits instead of waiting for motivation.",
     ["Choose one movement, one connection, and one rest habit weekly.",
      "Keep crisis numbers saved in your phone.",
      "Maintain a short list of people you can text honestly.",
      "Schedule enjoyable activities, not only duties.",
      "Review the toolkit monthly and drop what does not help.",
      "Professional care remains appropriate alongside self-care tools."]),
]

TOPICS["tests"] = [
    ("evergreen-tests-1", "What fasting before a blood test means",
     "Clear instructions prevent misleading results.",
     ["Fasting usually means no food for a set number of hours, often eight to twelve.",
      "Water is commonly allowed unless told otherwise.",
      "Ask whether black coffee or medicines are permitted before your specific test.",
      "Bring your medicine list to the draw.",
      "Reschedule if you ate by mistake rather than guessing.",
      "Confirm how results will be communicated afterward."]),
    ("evergreen-tests-2", "Understanding a complete blood count",
     "CBC looks at red cells, white cells, and platelets.",
     ["Low red cells can relate to anemia from many causes.",
      "White cells may rise with infection or inflammation.",
      "Platelets matter for clotting and bleeding risk.",
      "Results need context from symptoms and other labs.",
      "Ask which values are most important for your case.",
      "Repeat tests sometimes confirm unexpected findings."]),
    ("evergreen-tests-3", "Blood sugar and HbA1c explained",
     "One checks now; the other reflects months of average sugar.",
     ["Fingerstick or lab glucose shows a moment in time.",
      "HbA1c estimates average sugar over roughly three months.",
      "Targets differ by age, pregnancy, and other conditions.",
      "Illness can temporarily raise glucose readings.",
      "Bring home logs to appointments if you monitor.",
      "Ask how diet and medicines will change based on results."]),
    ("evergreen-tests-4", "Cholesterol panels without panic",
     "Numbers guide risk talks alongside lifestyle and family history.",
     ["LDL, HDL, and triglycerides are read together.",
      "Fasting requirements depend on the lab protocol.",
      "High results do not mean immediate crisis for everyone.",
      "Clinicians combine lipids with blood pressure and smoking status.",
      "Lifestyle changes and medicines may both be options.",
      "Recheck intervals depend on your risk level."]),
    ("evergreen-tests-5", "Malaria testing when fever appears",
     "Timing and local methods matter for accuracy.",
     ["Seek testing promptly for fever in malaria regions or after travel there.",
      "Rapid tests and microscopy are common tools.",
      "A single negative test may need repeat if suspicion remains high.",
      "Do not wait for severe symptoms before testing when risk is high.",
      "Complete prescribed treatment fully if malaria is confirmed.",
      "Prevention with nets remains essential even after treatment."]),
    ("evergreen-tests-6", "Urine tests for infection and beyond",
     "A simple sample can reveal infection, sugar, or pregnancy.",
     ["Clean-catch technique reduces contamination.",
      "Drink enough to provide a sample but follow lab timing rules.",
      "Tell staff if you are on antibiotics already.",
      "Culture results may take longer than dipstick screens.",
      "Follow up so positives lead to the right medicine.",
      "Pregnancy tests have timing windows—ask if unsure."]),
    ("evergreen-tests-7", "ECG: what it can and cannot show",
     "An ECG records heart electrical patterns in minutes.",
     ["It can detect rhythm problems and some signs of heart strain.",
      "A normal ECG does not always rule out all heart disease.",
      "Tell technicians about chest symptoms happening during the test.",
      "Bring prior ECGs for comparison when available.",
      "Further tests like blood work or imaging may still be needed.",
      "Ask for a plain-language summary of major findings."]),
    ("evergreen-tests-8", "X-rays and radiation in plain words",
     "Benefits usually outweigh small radiation doses when indicated.",
     ["X-rays help assess bones, chest infections, and some abdominal issues.",
      "Tell staff if you might be pregnant before imaging.",
      "Lead shields may be used according to modern protocols.",
      "Ask why the image is needed and whether alternatives exist.",
      "Bring prior images to avoid repeats when possible.",
      "Results often need a radiologist report plus clinician explanation."]),
    ("evergreen-tests-9", "Ultrasound without ionizing radiation",
     "Sound waves create images for pregnancy, abdomen, and vessels.",
     ["Ultrasound does not use X-ray radiation.",
      "You may need a full bladder or fasting depending on the study.",
      "Wear comfortable clothing and arrive on time for gel prep.",
      "Ask whether you will receive images or only a report.",
      "Abnormal findings need clinical follow-up plans.",
      "Emergency ultrasound can speed care in trauma and pregnancy pain."]),
    ("evergreen-tests-10", "HIV and other STI testing basics",
     "Knowing status enables treatment and prevention for partners.",
     ["Testing windows matter after a possible exposure.",
      "Confidential services are available in many clinics.",
      "Positive results have effective treatments for several infections.",
      "Partner notification support exists in many programs.",
      "Retesting may be advised after treatment or new exposures.",
      "Vaccines and condoms remain prevention tools alongside testing."]),
    ("evergreen-tests-11", "Stool tests you might be asked for",
     "Samples detect parasites, blood, or infection depending on the order.",
     ["Follow collection instructions exactly, including timing.",
      "Do not contaminate samples with urine if the lab warns against it.",
      "Return samples within the time window given.",
      "Tell the lab about recent antibiotics or travel.",
      "Results guide targeted treatment rather than guesswork.",
      "Ask how you will receive and act on the report."]),
    ("evergreen-tests-12", "Blood pressure checks done right",
     "Technique errors create false high or low readings.",
     ["Sit quietly for a few minutes before measurement.",
      "Keep feet on the floor and arm supported at heart level.",
      "Use a cuff that fits your arm size.",
      "Avoid talking during the reading.",
      "Compare clinic and home devices if numbers disagree widely.",
      "Very high readings with symptoms need urgent care pathways."]),
    ("evergreen-tests-13", "Pregnancy scans and check timing",
     "Schedules vary; ask what each scan is looking for.",
     ["Early scans may confirm location and dates.",
      "Later scans assess growth and placenta position among other findings.",
      "Arrive with required paperwork and prior reports.",
      "Ask whether a full bladder is needed.",
      "Urgent scans may be arranged for bleeding or pain.",
      "Discuss results with your antenatal clinician, not only the imaging desk."]),
    ("evergreen-tests-14", "Allergy testing overview",
     "Skin or blood tests support—not replace—clinical history.",
     ["Share a detailed list of reactions and timings.",
      "Some medicines must stop before skin testing—follow instructions.",
      "Positive tests show sensitization, not always clinical allergy.",
      "Negative tests may still miss some triggers.",
      "Emergency plans remain important for prior anaphylaxis.",
      "Ask how results change avoidance or treatment plans."]),
    ("evergreen-tests-15", "Getting copies of your results",
     "Personal records improve continuity across facilities.",
     ["Request printed or electronic copies after visits.",
      "Store them with your personal health summary.",
      "Check names and dates for accuracy.",
      "Share prior results to reduce duplicate testing.",
      "Ask for explanations of abbreviations you do not understand.",
      "Keep sensitive results private on locked devices."]),
]

TOPICS["nutrition"] = [
    ("evergreen-nutrition-1", "Build a balanced plate without perfection",
     "Patterns across the week matter more than one perfect meal.",
     ["Fill half the plate with vegetables or fruits when you can.",
      "Add proteins such as beans, eggs, fish, or lean meats.",
      "Include whole grains or local staples for steady energy.",
      "Use oils and fats thoughtfully rather than eliminating them entirely.",
      "Skip all-or-nothing rules that collapse after one snack.",
      "Adjust portions to appetite, activity, and clinical advice."]),
    ("evergreen-nutrition-2", "Sugar, drinks, and steady energy",
     "Sweet drinks raise sugar quickly without lasting fullness.",
     ["Prefer water as the default daily drink.",
      "Limit sodas, energy drinks, and frequent sweet juices.",
      "Read labels for hidden sugars in packaged beverages.",
      "Pair sweet foods with protein or fiber when you choose them.",
      "People with diabetes need individualized drink guidance.",
      "Hydration still matters—plain water first."]),
    ("evergreen-nutrition-3", "Protein on a budget",
     "Beans, eggs, and small fish can cover needs affordably.",
     ["Cook beans in batches for several meals.",
      "Eggs are versatile when food safety storage is good.",
      "Dried fish or small portions of meat can stretch across stews.",
      "Combine grains and legumes across the day for variety.",
      "Ask clinicians about protein needs in kidney disease—limits may apply.",
      "Protein supports healing, immunity, and muscle maintenance."]),
    ("evergreen-nutrition-4", "Fiber for digestion and fullness",
     "Vegetables, fruits, beans, and whole grains support gut comfort.",
     ["Increase fiber gradually to reduce bloating.",
      "Drink water as fiber intake rises.",
      "Whole fruits usually beat frequent fruit juice for fiber.",
      "Constipation often improves with fiber, fluids, and walking.",
      "Sudden severe abdominal pain still needs clinical review.",
      "Some gut conditions need tailored fiber advice—ask first."]),
    ("evergreen-nutrition-5", "Salt smarter at home",
     "Flavor can stay high while sodium comes down.",
     ["Taste food before automatically adding salt.",
      "Use herbs, citrus, garlic, and pepper for flavor.",
      "Cut back gradually so preferences adapt.",
      "Watch packaged seasonings and instant noodles for hidden salt.",
      "Heart and kidney conditions may need stricter limits.",
      "Ask what daily target fits your medicines and labs."]),
    ("evergreen-fitness-1", "Walking as medicine you can start today",
     "Brisk walking improves heart, mood, and blood sugar control.",
     ["Start with ten comfortable minutes if you are new to activity.",
      "Build toward most days of the week.",
      "Wear supportive shoes and choose safer routes and times.",
      "Use talking pace as a guide—you should still converse.",
      "Stop for chest pain or severe breathlessness.",
      "Track streaks rather than perfection to stay consistent."]),
    ("evergreen-fitness-2", "Strength without a gym membership",
     "Bodyweight moves protect muscle as we age.",
     ["Try sit-to-stands from a chair for leg strength.",
      "Wall push-ups build upper body safely for beginners.",
      "Carry groceries with good posture as functional training.",
      "Two sessions weekly already help many adults.",
      "Breathe steadily; do not hold breath during strain.",
      "Get advice before heavy lifting with hernia, heart, or joint disease."]),
    ("evergreen-fitness-3", "Warm-ups and injury prevention",
     "A few minutes of prep reduce strains.",
     ["Start with easy movement before harder effort.",
      "Increase distance or intensity by small weekly steps.",
      "Rest sore areas that worsen with every session.",
      "Cross-train with different activities to share load.",
      "Replace worn shoes that cause foot or knee pain.",
      "Seek care for swelling, locking joints, or sharp pain."]),
    ("evergreen-fitness-4", "Activity with chronic conditions",
     "Most conditions benefit from tailored movement plans.",
     ["Ask clinicians what intensity is safe for you.",
      "Diabetes: carry quick sugar if medicines risk lows.",
      "Asthma: warm up and keep relievers accessible.",
      "Arthritis: prefer low-impact options like swimming or cycling.",
      "Heart disease: follow cardiac rehab guidance when available.",
      "Report new chest symptoms during exercise promptly."]),
    ("evergreen-fitness-5", "Rest days and recovery",
     "Progress needs recovery as much as effort.",
     ["Schedule easier days between hard sessions.",
      "Sleep is the foundation of recovery.",
      "Gentle walking on rest days beats total inactivity for many people.",
      "Persistent fatigue may mean you are progressing too fast.",
      "Hydrate and eat enough protein to support repair.",
      "Children and teens need rest to grow safely with sports."]),
    ("evergreen-nutrition-6", "Eating patterns during shift work",
     "Irregular hours challenge metabolism and sleep.",
     ["Anchor one consistent mealtime when possible.",
      "Pack balanced foods instead of relying only on vending snacks.",
      "Limit heavy greasy meals right before daytime sleep.",
      "Use caffeine earlier in the shift, not near planned sleep.",
      "Keep water visible during long shifts.",
      "Ask occupational health for tailored advice when available."]),
    ("evergreen-nutrition-7", "Healthy weight goals without shame",
     "Sustainable habits beat crash diets.",
     ["Focus on behaviors: meals, movement, sleep, and stress.",
      "Rapid extreme restriction often rebounds.",
      "Measure progress with energy, labs, and clothes—not only the scale.",
      "Medical conditions and medicines affect weight regulation.",
      "Seek clinical programs for obesity when lifestyle alone is not enough.",
      "Avoid products promising miracle overnight fat loss."]),
    ("evergreen-nutrition-8", "Hydration beyond the hype",
     "Thirst, urine color, and climate guide needs better than rigid liters.",
     ["Pale yellow urine often suggests adequate hydration for many people.",
      "Drink more in heat, illness with fever, or heavy sweating.",
      "Water is usually best; sugary drinks are not hydration heroes.",
      "Heart or kidney disease may need fluid limits—follow clinical advice.",
      "Oral rehydration helps during diarrhea when appropriate.",
      "Dizziness and dry mouth can signal you need fluids and rest."]),
    ("evergreen-nutrition-9", "Eating well in pregnancy and breastfeeding",
     "Needs rise; alcohol still does not belong.",
     ["Take recommended prenatal vitamins including folic acid guidance.",
      "Emphasize iron-rich foods and safe protein sources.",
      "Avoid alcohol while pregnant; discuss alcohol while breastfeeding with clinicians.",
      "Food safety reduces infection risks for mother and baby.",
      "Small frequent meals can ease nausea for some.",
      "Ask about local food assistance if access is limited."]),
    ("evergreen-nutrition-10", "Reading packaged food labels",
     "Serving size tricks hide sugar and salt.",
     ["Start with serving size before comparing numbers.",
      "Scan sugar, salt, and saturated fat per serving.",
      "Ingredient lists order items by amount.",
      "Beware multiple names for sugars on one label.",
      "Choose products you understand over marketing claims.",
      "Whole foods without labels still form the base of healthy patterns."]),
]


def main() -> None:
    catalog: dict[str, list[dict]] = {}
    for cat, items in TOPICS.items():
        if len(items) != 15:
            raise SystemExit(f"{cat} has {len(items)} topics, expected 15")
        catalog[cat] = [build_article(item) for item in items]
        for article in catalog[cat]:
            if word_count(article["content"]) < 100:
                raise SystemExit(f"{article['id']} under 100 words")

    OUT.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Wrote {OUT} with {len(catalog)} categories, {total} articles")
    for cat, arts in catalog.items():
        lengths = [word_count(a["content"]) for a in arts]
        print(f"  {cat}: {len(arts)} topics, words {min(lengths)}–{max(lengths)}")


if __name__ == "__main__":
    main()
