#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate i18n-apps-phrases-batch2.mjs from _apps-batch-2.json + translation rows."""
import json
from pathlib import Path

DIR = Path(__file__).parent
LOCALES = ["fr", "es", "yo", "ha", "ig", "sw", "tw", "zh", "hi"]

# [en, fr, es, yo, ha, ig, sw, tw, zh, hi] — 119 rows for strings missing from locale apps.json
GEN = [
    ["Estimated from your last menstrual period", "Estimé à partir de vos dernières règles", "Estimado según tu último periodo menstrual", "Ti a ṣe asọtẹlẹ lati akoko oyun rẹ ti tẹlẹ", "An kiyasta daga lokacin haidar ku na baya", "E kere site na oge gị gara aga", "Imekadiriwa kutokana na hedhi yako ya mwisho", "Wɔabɔ no fi wo last menstrual period", "根据末次月经估算", "आपके अंतिम मासिक धर्म से अनुमानित"],
    ["Every 2 years", "Tous les 2 ans", "Cada 2 años", "Ni ọdọọdún 2", "Kowace shekara 2", "Kwa afọ 2", "Kila miaka 2", "Mfe biara 2", "每 2 年", "हर 2 वर्ष"],
    ["Every 3 years", "Tous les 3 ans", "Cada 3 años", "Ni ọdọọdún 3", "Kowace shekara 3", "Kwa afọ 3", "Kila miaka 3", "Mfe biara 3", "每 3 年", "हर 3 वर्ष"],
    ["Every 5 years", "Tous les 5 ans", "Cada 5 años", "Ni ọdọọdún 5", "Kowace shekara 5", "Kwa afọ 5", "Kila miaka 5", "Mfe biara 5", "每 5 年", "हर 5 वर्ष"],
    ["Every year", "Chaque année", "Cada año", "Ni ọdọọdún kan", "Kowace shekara", "Kwa afọ", "Kila mwaka", "Afe biara", "每年", "हर वर्ष"],
    ["Excited", "Excité(e)", "Emocionado/a", "Inu dun", "Farin ciki", "Obi ụtọ", "Amefurahi", "Anigye", "兴奋", "उत्साहित"],
    ["Eye / vision exam", "Examen oculaire / de la vue", "Examen ocular / de la vista", "Iwadii oju / iran", "Binciken ido / gani", "Nyocha anya / nle anya", "Ukaguzi wa macho / uoni", "Eye / vision exam", "眼科/视力检查", "आँख/दृष्टि जांच"],
    ["Family setup collects date of birth for each child — that's what powers the vaccine schedule.", "La configuration Famille recueille la date de naissance de chaque enfant — c'est ce qui alimente le calendrier vaccinal.", "La configuración de familia recoge la fecha de nacimiento de cada niño — eso alimenta el calendario de vacunas.", "Iṣeto idile gba ọjọ ibi fun ọmọ kọọkan — eyi ni o ṣe agbara iṣeto ajẹsara.", "Saitin iyali yana tattara ranar haihuwar kowane yaro — hakan ne ke taimaka wa jadawalin rigakafi.", "Nhazi ezinụlọ na-anakọta ụbọchị ọmụmụ nke ọ bụla — nke a na-akwado usoro oge ọgwụ mgbochi.", "Usanidi wa familia hukusanya tarehe ya kuzaliwa kwa kila mtoto — hilo ndilo linaloendesha ratiba ya chanjo.", "Family setup gyee date of birth ma abofra biara — neɛ na ɛma vaccine schedule no tumi.", "家庭设置会收集每个孩子的出生日期——疫苗时间表由此生成。", "परिवार सेटअप प्रत्येक बच्चे की जन्म तिथि एकत्र करता है — यही टीका अनुसूची संचालित करता है।"],
    ["Fasting", "À jeun", "En ayunas", "Ajẹ", "Azumi", "Agụụ", "Bila chakula", "Afunu", "空腹", "उपवास"],
    ["Fasting glucose or HbA1c, especially with family history or excess weight.", "Glycémie à jeun ou HbA1c, surtout en cas d'antécédents familiaux ou de surpoids.", "Glucosa en ayunas o HbA1c, especialmente con antecedentes familiares o sobrepeso.", "Suga ẹjẹ ajẹ tabi HbA1c, pataki pẹlu itan idile tabi iwuwo ju.", "Glucose a azumi ko HbA1c, musamman idan akwai tarihin iyali ko nauyi mai yawa.", "Glucose agụụ ma ọ bụ HbA1c, kachasị na ndụmọdụ ezinụlọ ma ọ bụ ibu karịa.", "Sukari ya bila chakula au HbA1c, hasa ikiwa kuna historia ya familia au uzito kupita kiasi.", "Fasting glucose anaa HbA1c, sɛ wo wɔ family history anaa excess weight.", "空腹血糖或 HbA1c，尤其有家族史或超重时。", "उपवास ग्लूकोज या HbA1c, विशेषकर पारिवारिक इतिहास या अतिरिक्त वजन हो तो।"],
    ["Fatigue", "Fatigue", "Fatiga", "Arun", "Gajiya", "Ị na-arụ ọrụ", "Uchovu", "M'abrɛ", "疲劳", "थकान"],
    ["Feet", "Pieds", "Pies", "Ẹsẹ", "Kafafu", "Ụkwụ", "Miguu", "Ananmu", "英尺", "फीट"],
    ["Fertile", "Fertile", "Fértil", "Ti mọlẹ", "Mai haihuwa", "Na-amụ nwa", "Inayozaa", "Fertile", "易孕期", "उपजाऊ"],
    ["Finish", "Terminer", "Finalizar", "Parí", "Gama", "Mechie", "Maliza", "Wie", "完成", "समाप्त करें"],
    ["Finish postpartum care", "Terminer les soins post-partum", "Finalizar cuidado posparto", "Parí itọju lẹhin ibimọ", "Gama kula da bayan haihuwa", "Mechie nlekọta mgbe ị mụsịrị nwa", "Maliza utunzaji baada ya kujifungua", "Finish postpartum care", "结束产后护理", "प्रसवोत्तर देखभाल समाप्त करें"],
    ["Finish postpartum care?", "Terminer les soins post-partum ?", "¿Finalizar cuidado posparto?", "Parí itọju lẹhin ibimọ?", "A gama kula da bayan haihuwa?", "Mechie nlekọta mgbe ị mụsịrị nwa?", "Maliza utunzaji baada ya kujifungua?", "Finish postpartum care?", "结束产后护理？", "प्रसवोत्तर देखभाल समाप्त करें?"],
    ["Finish postpartum mother care first, then you can set up a new pregnancy timeline.", "Terminez d'abord les soins post-partum maternels, puis vous pourrez configurer une nouvelle chronologie de grossesse.", "Primero finaliza el cuidado posparto materno, luego podrás configurar una nueva línea de tiempo del embarazo.", "Parí itọju iya lẹhin ibimọ ni akọkọ, lẹhinna o le ṣeto akoko ibimọ tuntun.", "Ka fara gama kula da mahaifiya bayan haihuwa, sannan za ka iya saita sabon tsarin lokacin ciki.", "Mechie nlekọta nne mgbe ị mụsịrị nwa mbụ, mgbe ahụ ị nwere ike ịhazie usoro oge ime ime ọhụrụ.", "Maliza kwanza utunzaji wa mama baada ya kujifungua, kisha unaweza kuweka ratiba mpya ya ujauzito.", "Finish postpartum mother care ansa, na wo betumi ayɛ pregnancy timeline foforo.", "请先完成母亲产后护理，然后才能设置新的怀孕时间线。", "पहले मातृ प्रसवोत्तर देखभाल पूरी करें, फिर नई गर्भावस्था समयरेखा सेट कर सकते हैं।"],
    ["First dose given at birth or within 24 hours.", "Première dose administrée à la naissance ou dans les 24 heures.", "Primera dosis al nacer o dentro de las 24 horas.", "Iṣẹju akọkọ fun ni ibimọ tabi laarin wakati 24.", "An ba da ƙarar farko a haihuwa ko cikin sa'o'i 24.", "E nyere dozi mbụ na ọmụmụ ma ọ bụ n'ime awa 24.", "Dozi ya kwanza hutolewa kuzaliwa au ndani ya masaa 24.", "First dose wɔwoo anaa within 24 hours.", "首剂在出生时或 24 小时内接种。", "पहली खुराक जन्म पर या 24 घंटे के भीतर दी जाती है।"],
    ["First measles-rubella dose around 9 months.", "Première dose rougeole-rubéole vers 9 mois.", "Primera dosis de sarampión-rubéola alrededor de los 9 meses.", "Iṣẹju measles-rubella akọkọ ni ọsẹ 9.", "An ba da ƙarar farko na masurafa-rubella kusan watanni 9.", "Dozi measles-rubella mbụ gburugburu ọnwa 9.", "Dozi ya kwanza ya surua-panya takriban miezi 9.", "First measles-rubella dose wɔ sɛbɛn 9.", "首次麻疹-风疹疫苗约 9 个月。", "पहली खसरा-रूबेला खुराक लगभग 9 महीने पर।"],
    ["First prenatal visit", "Première visite prénatale", "Primera visita prenatal", "Abẹwo akọkọ ti oyun", "Ziyarar farko na kafin haihuwa", "Nleta mbụ tupu ime ime", "Ziara ya kwanza ya ujauzito", "First prenatal visit", "首次产前检查", "पहली प्रसवपूर्व मुलाकात"],
    ["First routine polio dose.", "Première dose de polio de routine.", "Primera dosis rutinaria de polio.", "Iṣẹju polio akọkọ ti o wọpọ.", "An ba da ƙarar farko ta daidaitaccen polio.", "Dozi polio mbụ na-ahụkarị.", "Dozi ya kwanza ya kawaida ya polio.", "First routine polio dose.", "首次常规脊灰疫苗。", "पहली नियमित पोलियो खुराक।"],
    ["First trimester", "Premier trimestre", "Primer trimestre", "Trimesta akọkọ", "Trimester na farko", "Trimesta mbụ", "Trimesta ya kwanza", "First trimester", "第一孕期", "पहली तिमाही"],
    ["Focus on your recovery. Your TT record stays here.", "Concentrez-vous sur votre rétablissement. Votre dossier TT reste ici.", "Concéntrate en tu recuperación. Tu registro TT permanece aquí.", "Fi ara si iwosan rẹ. Iwe TT rẹ wa nibi.", "Ka mai da hankali kan warkewarku. Rubutun TT ku yana nan.", "Lelee na ịgwọ gị. Ndekọ TT gị nọ ebe a.", "Zingatia uponyaji wako. Rekodi yako ya TT inabaki hapa.", "Focus on wo recovery. Wo TT record wɔ ha.", "专注于您的恢复。您的 TT 记录仍在此。", "अपनी रिकवरी पर ध्यान दें। आपका TT रिकॉर्ड यहीं रहेगा।"],
    ["Food cravings", "Envies alimentaires", "Antojos de comida", "Ifẹ ounjẹ", "Kishirwar abinci", "Mmasị nri", "Tamu la chakula", "Food cravings", "食物渴望", "भोजन की लालसा"],
    ["General medical checkup", "Bilan médical général", "Chequeo médico general", "Iwadii ilera gbogbogbo", "Binciken lafiya gaba ɗaya", "Nyocha ahụike zuru oke", "Ukaguzi wa jumla wa afya", "General medical checkup", "常规体检", "सामान्य चिकित्सा जांच"],
    ["Given {{date}}", "Administré le {{date}}", "Administrado el {{date}}", "Fun ni {{date}}", "An ba a {{date}}", "E nyere na {{date}}", "Imetolewa {{date}}", "Wɔde maa no {{date}}", "接种日期 {{date}}", "{{date}} को दिया गया"],
    ["Global", "Global", "Global", "Global", "Global", "Global", "Global", "Global", "全球", "वैश्विक"],
    ["Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "Global ({{code}})", "全球 ({{code}})", "वैश्विक ({{code}})"],
    ["Guidance only — talk with a clinician for personal advice.", "Conseils indicatifs uniquement — parlez avec un professionnel de santé pour un avis personnalisé.", "Solo orientación — habla con un profesional de salud para consejo personal.", "Imọran nikan — sọrọ pẹlu onisegun fun imọran ti ara rẹ.", "Jagora kawai — yi magana da likita don shawara ta sirri.", "Na ndụmọdụ nụ — gwa onye na-elekọta ahụike maka ndụmọdụ onwe gị.", "Mwongozo tu — zungumza na mtaalamu wa afya kwa ushauri binafsi.", "Guidance nko — ka kyerɛ clinician ma wo personal advice.", "仅供参考——请咨询临床人员获取个人建议。", "केवल मार्गदर्शन — व्यक्तिगत सलाह के लिए चिकित्सक से बात करें।"],
    ["Happy", "Heureux(se)", "Feliz", "Aláyọ", "Farin ciki", "Obi ụtọ", "Furaha", "Anigye", "开心", "खुश"],
    ["Headache", "Mal de tête", "Dolor de cabeza", "Irora ori", "Ciwon kai", "Isi owuwa", "Maumivu ya kichwa", "Ti", "头痛", "सिरदर्द"],
    ["Hearing check", "Contrôle auditif", "Control auditivo", "Iwadii gbọ", "Binciken ji", "Nyocha ntị", "Ukaguzi wa kusikia", "Hearing check", "听力检查", "श्रवण जांच"],
    ["Heart rate", "Fréquence cardiaque", "Frecuencia cardíaca", "Iṣẹ ọkan", "Bugun zuciya", "Ọnụ ọgụgụ obi", "Mapigo ya moyo", "Heart rate", "心率", "हृदय गति"],
    ["Heartburn", "Brûlures d'estomac", "Acidez estomacal", "Ina inu", "Ciwon ciki", "Inụ inụ", "Maumivu ya kifua", "Heartburn", "胃灼热", "सीने में जलन"],
    ["Height", "Taille", "Estatura", "Giga", "Tsayi", "Ogologo", "Urefu", "Height", "身高", "ऊँचाई"],
    ["Hepatitis B", "Hépatite B", "Hepatitis B", "Hepatitis B", "Hepatitis B", "Hepatitis B", "Hepatitis B", "Hepatitis B", "乙型肝炎", "हेपेटाइटिस B"],
    ["How are you feeling?", "Comment vous sentez-vous ?", "¿Cómo te sientes?", "Báwo ni o ṣe rí?", "Yaya kake ji?", "Kedu ka ị na-ahụ?", "Unajisikiaje?", "Wo ho sɛn?", "您感觉如何？", "आप कैसा महसूस कर रहे हैं?"],
    ["How are you feeling? Any questions for your next visit?", "Comment vous sentez-vous ? Des questions pour votre prochaine visite ?", "¿Cómo te sientes? ¿Alguna pregunta para tu próxima visita?", "Báwo ni o ṣe rí? Ṣe o ni ibeere fun abẹwo rẹ ti o kan?", "Yaya kake ji? Akwai tambayoyi don ziyararku na gaba?", "Kedu ka ị na-ahụ? Ị nwere ajụjụ maka nleta gị na-abịa?", "Unajisikiaje? Maswali yoyote kwa ziara yako ijayo?", "Wo ho sɛn? Wɔwɔ nsɛm biara ma wo visit a ɛreba?", "您感觉如何？下次就诊有什么问题吗？", "आप कैसा महसूस कर रहे हैं? अगली विज़िट के लिए कोई प्रश्न?"],
    ["Inactivated polio booster around 6 months.", "Rappel polio inactivé vers 6 mois.", "Refuerzo de polio inactivada alrededor de los 6 meses.", "Atunṣe polio ti ko ṣiṣẹ ni ọsẹ 6.", "An ba da ƙarin rigakafin polio da ba a riga ba kusan watanni 6.", "Booster polio a kwụsịrị gburugburu ọnwa 6.", "Booster ya polio isiyofanyiwa takriban miezi 6.", "Inactivated polio booster wɔ sɛbɛn 6.", "约 6 个月接种灭活脊灰加强针。", "लगभग 6 महीने पर निष्क्रिय पोलियो बूस्टर।"],
    ["Inches", "Pouces", "Pulgadas", "Inches", "Inches", "Inches", "Inchi", "Inches", "英寸", "इंच"],
    ["Increase average cycle length", "Augmenter la durée moyenne du cycle", "Aumentar la duración promedio del ciclo", "Mu igba iyipo apapọ pọ si", "Ƙara tsawon zagayowar matsakaici", "Mee ogologo agafé nkezi ka buru ibu", "Ongeza urefu wa wastani wa mzunguko", "Increase average cycle length", "增加平均周期长度", "औसत चक्र अवधि बढ़ाएँ"],
    ["Insomnia", "Insomnie", "Insomnio", "Aisun", "Barci ba ya zuwa", "Enweghị ịra ụra", "Usingizi hauji", "Insomnia", "失眠", "अनिद्रा"],
    ["It has been at least 4 weeks since TT1. Ask your clinic about your next tetanus (TT) dose.", "Au moins 4 semaines se sont écoulées depuis TT1. Demandez à votre clinique la prochaine dose de tétanos (TT).", "Han pasado al menos 4 semanas desde TT1. Pregunta en tu clínica por tu próxima dosis de tétanos (TT).", "O ti jẹ o kere ju ọsẹ 4 lati TT1. Beere kliniki rẹ nipa iṣẹju tetanus (TT) rẹ ti o kan.", "An wuce makonni 4 tun TT1. Tambayi likitocinku game da ƙarar tetanus (TT) na gaba.", "O gafere izu 4 kemgbe TT1. Jụọ clinic gị maka dozi tetanus (TT) gị na-abịa.", "Imepita angalau wiki 4 tangu TT1. Uliza kliniki yako kuhusu dozi yako ijayo ya pepo (TT).", "At least 4 weeks since TT1. Bisa wo clinic fa wo next tetanus (TT) dose.", "距 TT1 已至少 4 周。请向诊所咨询下一剂破伤风 (TT) 疫苗。", "TT1 के बाद कम से कम 4 सप्ताह हो गए। अगली टेटanus (TT) खुराक के लिए क्लिनिक से पूछें।"],
    ["Journey", "Parcours", "Recorrido", "Irìn-àjò", "Tafiya", "Njem", "Safari", "Journey", "历程", "यात्रा"],
    ["Kicks logged", "Coups enregistrés", "Patadas registradas", "Awọn gbigbe ti a kọ", "An rubuta buga", "E depụtara mkpọtụ", "Matemo yaliyorekodiwa", "Kicks logged", "已记录胎动", "लातें दर्ज"],
    ["Last period", "Dernières règles", "Último periodo", "Akoko ti tẹlẹ", "Lokaci na baya", "Oge gara aga", "Hedhi ya mwisho", "Last period", "末次月经", "अंतिम मासिक धर्म"],
    ["Latest readings", "Dernières mesures", "Últimas lecturas", "Awọn kika ti tẹlẹ", "Karatu na baya", "Ngụkọta kachasị", "Usomaji wa hivi karibuni", "Latest readings", "最新读数", "नवीनतम रीडिंग"],
    ["Log TT1", "Enregistrer TT1", "Registrar TT1", "Kọ TT1", "Rubuta TT1", "Dekọ TT1", "Andika TT1", "Log TT1", "记录 TT1", "TT1 दर्ज करें"],
    ["Log anyway", "Enregistrer quand même", "Registrar de todos modos", "Kọ lọna", "Rubuta duk da haka", "Dekọ ka ọ dị", "Andika hata hivyo", "Log anyway", "仍要记录", "फिर भी दर्ज करें"],
    ["Log doses in order. Next expected is {{next}} (tried {{dose}}).", "Enregistrez les doses dans l'ordre. La prochaine attendue est {{next}} (vous avez essayé {{dose}}).", "Registra las dosis en orden. La siguiente esperada es {{next}} (intentaste {{dose}}).", "Kọ awọn iṣẹju ni ibere. Ti a nireti ti o kan jẹ {{next}} (o gbiyanju {{dose}}).", "Rubuta ƙarorin bisa tsari. Na gaba da ake tsammani shine {{next}} (ka gwada {{dose}}).", "Dekọ dozi n'usoro. Nke a na-atụ anya na-abịa bụ {{next}} (ị gbalịrị {{dose}}).", "Andika dozi kwa mpangilio. Inayotarajiwa ijayo ni {{next}} (ulijaribu {{dose}}).", "Log doses in order. Next expected yɛ {{next}} (tried {{dose}}).", "请按顺序记录。下一剂应为 {{next}}（您尝试了 {{dose}}）。", "खुराक क्रम में दर्ज करें। अगली अपेक्षित {{next}} है ({{dose}} आज़माया)।"],
    ["Log how you feel", "Enregistrer ce que vous ressentez", "Registra cómo te sientes", "Kọ bí o ṣe rí", "Rubuta yadda kake ji", "Dekọ ka ị na-ahụ", "Andika unavyojisikia", "Log how you feel", "记录您的感受", "अपनी अनुभूति दर्ज करें"],
    ["Log how you feel today", "Enregistrer ce que vous ressentez aujourd'hui", "Registra cómo te sientes hoy", "Kọ bí o ṣe rí loni", "Rubuta yadda kake ji yau", "Dekọ ka ị na-ahụ taa", "Andika unavyojisikia leo", "Log how you feel nnɛ", "记录您今天的感受", "आज की अनुभूति दर्ज करें"],
    ["Log how you're feeling today. This helps you spot patterns over time.", "Enregistrez ce que vous ressentez aujourd'hui. Cela vous aide à repérer des tendances au fil du temps.", "Registra cómo te sientes hoy. Esto te ayuda a detectar patrones con el tiempo.", "Kọ bí o ṣe rí loni. Eyi ran ọ lọwọ lati ri awọn aṣa lori akoko.", "Rubuta yadda kake ji yau. Wannan yana taimaka maka gano tsari a lokaci.", "Dekọ ka ị na-ahụ taa. Nke a na-enyere gị aka ịhụ usoro ka oge na-aga.", "Andika unavyojisikia leo. Hii inakusaidia kuona mifumo kwa muda.", "Log how wo feel nnɛ. Eyi boa wo hu patterns over time.", "记录您今天的感受。这有助于发现长期规律。", "आज की अनुभूति दर्ज करें। समय के साथ पैटर्न देखने में मदद करता है।"],
    ["Log next TT", "Enregistrer la prochaine TT", "Registrar siguiente TT", "Kọ TT ti o kan", "Rubuta TT na gaba", "Dekọ TT na-abịa", "Andika TT inayofuata", "Log next TT", "记录下一剂 TT", "अगली TT दर्ज करें"],
    ["Log that you completed this checkup for {{year}}. You can undo later from this screen.", "Enregistrez que vous avez effectué ce bilan pour {{year}}. Vous pourrez annuler plus tard depuis cet écran.", "Registra que completaste este chequeo para {{year}}. Puedes deshacerlo después desde esta pantalla.", "Kọ pe o ti pari iṣayẹwo yii fun {{year}}. O le da pada lẹhin lati iboju yii.", "Rubuta cewa ka kammala wannan binciken don {{year}}. Za ka iya soke daga baya daga wannan allo.", "Dekọ na ị mechara nyocha a maka {{year}}. Ị nwere ike weghachi mgbe emechaa site na ihuenyo a.", "Andika kwamba umekamilisha ukaguzi huu kwa {{year}}. Unaweza kutengua baadaye kutoka skrini hii.", "Log sɛ woayɛ checkup yi ma {{year}}. Wobetumi asan fi screen yi so akyiri.", "记录您已完成 {{year}} 年的此项体检。可稍后在此屏幕撤销。", "{{year}} के लिए यह जांच पूरी दर्ज करें। बाद में इस स्क्रीन से पूर्ववत कर सकते हैं।"],
    ["Log when this vaccine was given. You can update or remove the record later.", "Enregistrez la date de ce vaccin. Vous pourrez mettre à jour ou supprimer l'enregistrement plus tard.", "Registra cuándo se administró esta vacuna. Puedes actualizar o eliminar el registro después.", "Kọ nigbati a fun ajẹsara yii. O le ṣe imudojuiwọn tabi yọ iwe kọ lẹhin.", "Rubuta lokacin da aka ba wannan rigakafi. Za ka iya sabunta ko cire rubutun daga baya.", "Dekọ mgbe e nyere ọgwụ mgbochi a. Ị nwere ike melite ma ọ bụ wepụ ndekọ mgbe emechaa.", "Andika wakati chanjo hii ilitolewa. Unaweza kusasisha au kuondoa rekodi baadaye.", "Log bere a wɔde vaccine yi. Wobetumi update anaa remove record no akyiri.", "记录此疫苗接种日期。可稍后更新或删除记录。", "यह टीका कब लगा दर्ज करें। बाद में रिकॉर्ड अपडेट या हटा सकते हैं।"],
    ["Log {{dose}}", "Enregistrer {{dose}}", "Registrar {{dose}}", "Kọ {{dose}}", "Rubuta {{dose}}", "Dekọ {{dose}}", "Andika {{dose}}", "Log {{dose}}", "记录 {{dose}}", "{{dose}} दर्ज करें"],
    ["Logged days", "Jours enregistrés", "Días registrados", "Awọn ọjọ ti a kọ", "Kwanakin da aka rubuta", "Ụbọchị edebanyere", "Siku zilizoandikwa", "Logged days", "已记录天数", "दर्ज दिन"],
    ["Logged period", "Règles enregistrées", "Periodo registrado", "Akoko ti a kọ", "Lokacin da aka rubuta", "Oge edebanyere", "Hedhi iliyoandikwa", "Logged period", "已记录经期", "दर्ज मासिक धर्म"],
    ["Mammogram", "Mammographie", "Mamografía", "Mammogram", "Mammogram", "Mammogram", "Mammogram", "Mammogram", "乳腺 X 光", "मैमोग्राम"],
    ["Mark done for {{year}}", "Marquer comme fait pour {{year}}", "Marcar como hecho para {{year}}", "Samisi pe o ti pari fun {{year}}", "Yi alama an gama don {{year}}", "Kaa ka emechara maka {{year}}", "Weka alama umekamilika kwa {{year}}", "Mark done ma {{year}}", "标记 {{year}} 年已完成", "{{year}} के लिए पूर्ण चिह्नित करें"],
    ["Measles / MR", "Rougeole / RR", "Sarampión / SR", "Measles / MR", "Measles / MR", "Measles / MR", "Surua / MR", "Measles / MR", "麻疹 / MR", "खसरा / MR"],
    ["Mid-pregnancy ultrasound around 18–22 weeks.", "Échographie de mi-grossesse vers 18–22 semaines.", "Ecografía a mitad del embarazo alrededor de las 18–22 semanas.", "Ultrasound laarin ibimọ ni ọsẹ 18–22.", "Ultrasound na tsakiyar ciki kusan makonni 18–22.", "Ultrasound etiti ime ime gburugburu izu 18–22.", "Ultrasound ya katikati ya ujauzito takriban wiki 18–22.", "Mid-pregnancy ultrasound wɔ sɛbɛn 18–22.", "孕中期超声约 18–22 周。", "गर्भावस्था के मध्य में अल्ट्रासाउंड लगभग 18–22 सप्ताह।"],
    ["Milestones", "Étapes", "Hitos", "Awọn aṣa pataki", "Muhimman matakai", "Ihe dị mkpa", "Hatua muhimu", "Milestones", "里程碑", "मीलस्टोन"],
    ["Mood", "Humeur", "Estado de ánimo", "Iṣọrọ", "Yanayi", "Obi ihe", "Hali", "Mood", "心情", "मूड"],
    ["Mother care", "Soins maternels", "Cuidado materno", "Itọju iya", "Kula da mahaifiya", "Nlekọta nne", "Utunzaji wa mama", "Mother care", "母婴护理", "मातृ देखभाल"],
    ["Nausea", "Nausée", "Náuseas", "Irora inu", "Kumburin ciki", "Mgbu afọ", "Kichefuchefu", "Nausea", "恶心", "मितली"],
    ["Next predicted period: {{range}}", "Prochaines règles prévues : {{range}}", "Próximo periodo previsto: {{range}}", "Akoko ti a ṣe asọtẹlẹ ti o kan: {{range}}", "Lokacin da aka hasashe na gaba: {{range}}", "Oge a na-atụ anya na-abịa: {{range}}", "Hedhi inayotarajiwa: {{range}}", "Next predicted period: {{range}}", "下次预测月经：{{range}}", "अगली अनुमानित मासिक धर्म: {{range}}"],
    ["Next steps", "Prochaines étapes", "Próximos pasos", "Awọn igbesẹ ti o kan", "Matakan na gaba", "Usoro na-abịa", "Hatua zijazo", "Next steps", "后续步骤", "अगले कदम"],
    ["Next up", "Ensuite", "Siguiente", "Ti o kan", "Na gaba", "Na-abịa", "Inayofuata", "Next up", "接下来", "अगला"],
    ["Next year ({{year}})", "L'année prochaine ({{year}})", "El próximo año ({{year}})", "Ọdun ti o kan ({{year}})", "Shekara mai zuwa ({{year}})", "Afọ na-abịa ({{year}})", "Mwaka ujao ({{year}})", "Afe a edi kan ({{year}})", "明年 ({{year}})", "अगले वर्ष ({{year}})"],
    ["Next: {{dose}}", "Suivant : {{dose}}", "Siguiente: {{dose}}", "Ti o kan: {{dose}}", "Na gaba: {{dose}}", "Ọzọ: {{dose}}", "Ifuatayo: {{dose}}", "Next: {{dose}}", "下一剂：{{dose}}", "अगली: {{dose}}"],
    ["Next: {{name}} ({{dose}})", "Suivant : {{name}} ({{dose}})", "Siguiente: {{name}} ({{dose}})", "Ti o kan: {{name}} ({{dose}})", "Na gaba: {{name}} ({{dose}})", "Ọzọ: {{name}} ({{dose}})", "Ifuatayo: {{name}} ({{dose}})", "Next: {{name}} ({{dose}})", "下一剂：{{name}} ({{dose}})", "अगली: {{name}} ({{dose}})"],
    ["No checkups listed for this year with your current profile.", "Aucun bilan listé pour cette année avec votre profil actuel.", "No hay chequeos listados para este año con tu perfil actual.", "Ko si awọn iṣayẹwo ti a ṣe atokọ fun ọdun yii pẹlu profaili rẹ lọwọlọwọ.", "Babu bincike da aka jera don wannan shekara tare da bayanan ku na yanzu.", "Enweghị nyocha edepụtara maka afọ a na profaịlụ gị ugbu a.", "Hakuna ukaguzi uliowekwa kwa mwaka huu na wasifu wako wa sasa.", "Checkups biara nni hɔ ma year yi wɔ wo profile mu.", "当前资料下今年没有列出的体检。", "आपकी वर्तमान प्रोफ़ाइल के साथ इस वर्ष कोई जांच सूचीबद्ध नहीं।"],
    ["No countries match that search.", "Aucun pays ne correspond à cette recherche.", "Ningún país coincide con esa búsqueda.", "Ko si orilẹ-ede kan ti o ba wiwa naa mu.", "Babu ƙasa da ta dace da wannan bincike.", "Enweghị obodo dabara na ọchụchọ ahụ.", "Hakuna nchi inayolingana na utafutaji huo.", "No countries match search no.", "没有匹配该搜索的国家。", "कोई देश इस खोज से मेल नहीं खाता।"],
    ["No daily logs were saved for this pregnancy.", "Aucun journal quotidien n'a été enregistré pour cette grossesse.", "No se guardaron registros diarios para este embarazo.", "Ko si awọn iwe akọsilẹ ojoojumọ ti a fi pamọ fun ibimọ yii.", "Ba a ajiye rubutun yau da kullum don wannan ciki ba.", "Enweghị ndekọ kwa ụbọchị echekwara maka ime ime a.", "Hakuna rekodi za kila siku zilizohifadhiwa kwa ujauzito huu.", "Daily logs biara nni hɔ ma pregnancy yi.", "此次怀孕没有保存日常日志。", "इस गर्भावस्था के लिए कोई दैनिक लॉग सहेजा नहीं गया।"],
    ["No reading yet", "Aucune mesure pour l'instant", "Sin lecturas aún", "Ko si kika sibẹ", "Har yanzu babu karatu", "Enweghị ngụkọta ugbu a", "Bado hakuna usomaji", "Reading biara nni hɔ", "尚无读数", "अभी कोई रीडिंग नहीं"],
    ["No symptoms logged yet today", "Aucun symptôme enregistré aujourd'hui", "Sin síntomas registrados hoy", "Ko si awọn àmì ti a kọ loni", "Har yanzu babu alamomi da aka rubuta yau", "Enweghị mgbaàmà edebanyere taa", "Bado hakuna dalili zilizorekodiwa leo", "Symptoms biara nni hɔ nnɛ", "今天尚未记录症状", "आज अभी कोई लक्षण दर्ज नहीं"],
    ["Not logged", "Non enregistré", "No registrado", "Ko ti kọ", "Ba a rubuta ba", "Edebeghị", "Haijaandikwa", "Wɔnkyerɛw", "未记录", "दर्ज नहीं"],
    ["Notes", "Notes", "Notas", "Awọn akọsilẹ", "Bayanan kula", "Ihe edeturu", "Maelezo", "Notes", "备注", "नोट्स"],
    ["Notes (optional)", "Notes (facultatif)", "Notas (opcional)", "Awọn akọsilẹ (aṣayan)", "Bayanan kula (na zaɓi)", "Ihe edeturu (nhọrọ)", "Maelezo (si lazima)", "Notes (ɛnyɛ ɔhyɛ)", "备注（可选）", "नोट्स (वैकल्पिक)"],
    ["Nothing is filled in for today. Save an empty log anyway?", "Rien n'est rempli pour aujourd'hui. Enregistrer un journal vide quand même ?", "No hay nada completado para hoy. ¿Guardar un registro vacío de todos modos?", "Ko si nkankan ti a kun fun loni. Fi iwe akọsilẹ sofo pamọ lọna?", "Ba a cika komai don yau ba. A ajiye rubutun maras komai duk da haka?", "Edebereghị ihe maka taa. Ị chọrọ ichekwaa ndekọ efu?", "Hakuna kilichojazwa kwa leo. Hifadhi rekodi tupu hata hivyo?", "Biribiara nni hɔ nnɛ. Save empty log anyway?", "今天未填写任何内容。仍要保存空日志？", "आज कुछ भरा नहीं है। फिर भी खाली लॉग सहेजें?"],
    ["Once (when due)", "Une fois (quand dû)", "Una vez (cuando corresponda)", "Lẹẹkan (nigba ti o yẹ)", "Sau ɗaya (lokacin da ya dace)", "Otu oge (mgbe o kwesịrị)", "Mara moja (inapostahili)", "Once (when due)", "一次（到期时）", "एक बार (नियत होने पर)"],
    ["Ongoing", "En cours", "En curso", "Ti n lọ lọwọ", "Ana ci gaba", "Na-aga n'ihu", "Inaendelea", "Ongoing", "进行中", "चालू"],
    ["Open Pregnancy Tracker", "Ouvrir Suivi de grossesse", "Abrir Seguimiento del embarazo", "Ṣii Titele Ibimọ", "Buɗe Bin Diddigin Ciki", "Mepee Nsochi Ime Ime", "Fungua Ufuatiliaji wa Ujauzito", "Open Pregnancy Tracker", "打开怀孕追踪", "गर्भावस्था ट्रैकर खोलें"],
    ["Optional", "Facultatif", "Opcional", "Aṣayan", "Na zaɓi", "Nhọrọ", "Si lazima", "Ɛnyɛ ɔhyɛ", "可选", "वैकल्पिक"],
    ["Optional. Enter your weight in kilograms.", "Facultatif. Entrez votre poids en kilogrammes.", "Opcional. Ingresa tu peso en kilogramos.", "Aṣayan. Tẹ iwuwo rẹ ni kilogiramu.", "Na zaɓi. Shigar da nauyinku a kilogiram.", "Nhọrọ. Tinye ibu gị na kilogram.", "Si lazima. Weka uzito wako kwa kilogramu.", "Optional. Enter wo weight wɔ kilograms.", "可选。以千克输入体重。", "वैकल्पिक। वजन किलोग्राम में दर्ज करें।"],
    ["Other / prefer not to say", "Autre / préfère ne pas répondre", "Otro / prefiero no decir", "Miiran / maṣe fẹ sọ", "Sauran / ba na son faɗi ba", "Ọzọ / achọghị ikwu", "Nyingine / sipendi kusema", "Other / prefer not to say", "其他 / 不愿透露", "अन्य / नहीं बताना चाहते"],
    ["Overdue", "En retard", "Atrasado", "Ti kọja", "Ya wuce lokaci", "Gafere", "Imechelewa", "Overdue", "逾期", "अतिदेय"],
    ["Ovulation", "Ovulation", "Ovulación", "Imu omo", "Ovulation", "Ovulation", "Ovulation", "Ovulation", "排卵", "ओव्यूलेशन"],
    ["Oxygen saturation", "Saturation en oxygène", "Saturación de oxígeno", "Ipe oksijẹn", "Cikakken oksijin", "Ogo oxygen", "Ujazo wa oksijeni", "Oxygen saturation", "血氧饱和度", "ऑक्सीजन संतृप्ति"],
    ["Past due", "Date dépassée", "Fecha vencida", "Ti kọja ọjọ", "Ya wuce ranar", "Gafere ụbọchị", "Imepita tarehe", "Past due", "已过日期", "तारीख बीत चुकी"],
    ["Past pregnancies", "Grossesses passées", "Embarazos anteriores", "Awọn ibimọ ti tẹlẹ", "Cikin da suka wuce", "Ime ime gara aga", "Ujauzito uliopita", "Past pregnancies", "以往怀孕", "पिछली गर्भावस्थाएँ"],
    ["Pause period tracking", "Mettre en pause le suivi des règles", "Pausar seguimiento del periodo", "Da titẹle akoko duro", "Dakatar da bin diddigin lokaci", "Kwụsị nsochi oge", "Simamisha ufuatiliaji wa hedhi", "Pause period tracking", "暂停经期追踪", "मासिक धर्म ट्रैकिंग रोकें"],
    ["Paused while you're pregnant. Your logged history is still here.", "En pause pendant votre grossesse. Votre historique enregistré reste ici.", "Pausado mientras estás embarazada. Tu historial registrado sigue aquí.", "Ti duro nigba ti o ba ni oyun. Itan rẹ ti a kọ wa nibi.", "An dakatar yayin da kake da ciki. Tarihin da ka rubuta yana nan.", "Kwụsịrị mgbe ị dị ime. Akụkọ ihe mere gị edebanyere ka nọ ebe a.", "Imesimamishwa ukiwa mjamzito. Historia yako iliyoandikwa bado iko hapa.", "Paused bere a wo wɔ pregnant. Wo logged history wɔ ha.", "怀孕期间已暂停。已记录的历史仍在此。", "गर्भवती होने पर रोकी गई। दर्ज इतिहास यहीं है।"],
    ["Pentavalent", "Pentavalent", "Pentavalente", "Pentavalent", "Pentavalent", "Pentavalent", "Pentavalent", "Pentavalent", "五联疫苗", "पेंटावैलेंट"],
    ["Period length", "Durée des règles", "Duración del periodo", "Ipari akoko", "Tsawon lokaci", "Ogologo oge", "Urefu wa hedhi", "Period length", "经期长度", "मासिक धर्म अवधि"],
    ["Period tracking is paused. Resume tracking to log days.", "Le suivi des règles est en pause. Reprenez le suivi pour enregistrer des jours.", "El seguimiento del periodo está en pausa. Reanuda para registrar días.", "Titẹle akoko ti duro. Tun bẹrẹ titẹle lati kọ awọn ọjọ.", "An dakatar da bin diddigin lokaci. Dawo da bin diddigi don rubuta kwanaki.", "Enyocha oge kwụsịrị. Maliteghachi iji dekọ ụbọchị.", "Ufuatiliaji wa hedhi umesimamishwa. Endelea ili kuandika siku.", "Period tracking agyina. Resume tracking na log days.", "经期追踪已暂停。恢复追踪以记录天数。", "मासिक धर्म ट्रैकिंग रोकी है। दिन दर्ज करने के लिए फिर शुरू करें।"],
    ["Period tracking paused", "Suivi des règles en pause", "Seguimiento del periodo en pausa", "Titẹle akoko ti duro", "An dakatar da bin diddigin lokaci", "Enyocha oge kwụsịrị", "Ufuatiliaji wa hedhi umesimamishwa", "Period tracking agyina", "经期追踪已暂停", "मासिक धर्म ट्रैकिंग रोकी"],
    ["Pick a date", "Choisir une date", "Elegir una fecha", "Yan ọjọ kan", "Zaɓi wata", "Họrọ ụbọchị", "Chagua tarehe", "Paw da", "选择日期", "तारीख चुनें"],
    ["Pick an end date on or after the start date.", "Choisissez une date de fin égale ou postérieure à la date de début.", "Elige una fecha de fin igual o posterior a la de inicio.", "Yan ọjọ ipari lori tabi lẹhin ọjọ ibẹrẹ.", "Zaɓi ranar ƙarewa a ranar farawa ko bayanta.", "Họrọ ụbọchị ngwụcha na ma ọ bụ mgbe e bidoro.", "Chagua tarehe ya mwisho siku ya kuanza au baadaye.", "Paw end date a ɛyɛ anaa a edi start date no akyi.", "选择结束日期，须不早于开始日期。", "समाप्ति तारीख शुरू तारीख के बराबर या बाद की चुनें।"],
    ["Please check this", "Veuillez vérifier ceci", "Por favor revisa esto", "Jọwọ ṣayẹwo eyi", "Da fatan za a duba wannan", "Biko nyochaa nke a", "Tafadhali angalia hii", "Please check this", "请检查此项", "कृपया इसे जाँचें"],
    ["Please check this reading", "Veuillez vérifier cette mesure", "Por favor revisa esta lectura", "Jọwọ ṣayẹwo kika yii", "Da fatan za a duba wannan karatu", "Biko nyochaa ngụkọta a", "Tafadhali angalia usomaji huu", "Please check reading no", "请检查此读数", "कृपया यह रीडिंग जाँचें"],
    ["Please choose a date before saving.", "Veuillez choisir une date avant d'enregistrer.", "Elige una fecha antes de guardar.", "Jọwọ yan ọjọ kan ṣaaju fifipamọ.", "Da fatan za a zaɓi wata kafin ajiyewa.", "Biko họrọ ụbọchị tupu ịchekwa.", "Tafadhali chagua tarehe kabla ya kuhifadhi.", "Choose date ansa na wo save.", "保存前请选择日期。", "सहेजने से पहले तारीख चुनें।"],
    ["Please choose a gender option before saving.", "Veuillez choisir une option de genre avant d'enregistrer.", "Elige una opción de género antes de guardar.", "Jọwọ yan aṣayan akọ kan ṣaaju fifipamọ.", "Da fatan za a zaɓi zaɓin jinsi kafin ajiyewa.", "Biko họrọ nhọrọ okike tupu ịchekwa.", "Tafadhali chagua chaguo la jinsia kabla ya kuhifadhi.", "Choose gender option ansa na wo save.", "保存前请选择性别选项。", "सहेजने से पहले लिंग विकल्प चुनें।"],
    ["Please choose a start date before saving.", "Veuillez choisir une date de début avant d'enregistrer.", "Elige una fecha de inicio antes de guardar.", "Jọwọ yan ọjọ ibẹrẹ kan ṣaaju fifipamọ.", "Da fatan za a zaɓi ranar farawa kafin ajiyewa.", "Biko họrọ ụbọchị mmalite tupu ịchekwa.", "Tafadhali chagua tarehe ya kuanza kabla ya kuhifadhi.", "Choose start date ansa na wo save.", "保存前请选择开始日期。", "सहेजने से पहले शुरू तारीख चुनें।"],
    ["Please choose the date this vaccine was given.", "Veuillez choisir la date d'administration de ce vaccin.", "Elige la fecha en que se administró esta vacuna.", "Jọwọ yan ọjọ ti a fun ajẹsara yii.", "Da fatan za a zaɓi ranar da aka ba wannan rigakafi.", "Biko họrọ ụbọchị e nyere ọgwụ mgbochi a.", "Tafadhali chagua tarehe chanjo hii ilitolewa.", "Choose date a wɔde vaccine yi.", "请选择此疫苗接种日期。", "कृपया यह टीका कब लगा चुनें।"],
    ["Please choose your date of birth before saving.", "Veuillez choisir votre date de naissance avant d'enregistrer.", "Elige tu fecha de nacimiento antes de guardar.", "Jọwọ yan ọjọ ibi rẹ ṣaaju fifipamọ.", "Da fatan za a zaɓi ranar haihuwarku kafin ajiyewa.", "Biko họrọ ụbọchị ọmụmụ gị tupu ịchekwa.", "Tafadhali chagua tarehe yako ya kuzaliwa kabla ya kuhifadhi.", "Choose wo date of birth ansa na wo save.", "保存前请选择出生日期。", "सहेजने से पहले जन्म तिथि चुनें।"],
    ["Please confirm", "Veuillez confirmer", "Por favor confirma", "Jọwọ jẹrisi", "Da fatan za a tabbatar", "Biko kwado", "Tafadhali thibitisha", "Please confirm", "请确认", "कृपया पुष्टि करें"],
    ["Please enter a reading before saving.", "Veuillez entrer une mesure avant d'enregistrer.", "Ingresa una lectura antes de guardar.", "Jọwọ tẹ kika kan ṣaaju fifipamọ.", "Da fatan za a shigar da karatu kafin ajiyewa.", "Biko tinye ngụkọta tupu ịchekwa.", "Tafadhali weka usomaji kabla ya kuhifadhi.", "Enter reading ansa na wo save.", "保存前请输入读数。", "सहेजने से पहले रीडिंग दर्ज करें।"],
    ["Please enter the dosage (for example 500mg) before saving.", "Veuillez entrer le dosage (par exemple 500 mg) avant d'enregistrer.", "Ingresa la dosis (por ejemplo 500 mg) antes de guardar.", "Jọwọ tẹ iṣẹju (fun apẹẹrẹ 500mg) ṣaaju fifipamọ.", "Da fatan za a shigar da ƙarar (misali 500mg) kafin ajiyewa.", "Biko tinye oke (dị ka 500mg) tupu ịchekwa.", "Tafadhali weka kipimo (kwa mfano 500mg) kabla ya kuhifadhi.", "Enter dosage (sɛ 500mg) ansa na wo save.", "保存前请输入剂量（例如 500mg）。", "सहेजने से पहले खुराक दर्ज करें (उदा. 500mg)।"],
    ["Please enter the medicine name before saving.", "Veuillez entrer le nom du médicament avant d'enregistrer.", "Ingresa el nombre del medicamento antes de guardar.", "Jọwọ tẹ orukọ oogun ṣaaju fifipamọ.", "Da fatan za a shigar da sunan magani kafin ajiyewa.", "Biko tinye aha ọgwụ tupu ịchekwa.", "Tafadhali weka jina la dawa kabla ya kuhifadhi.", "Enter medicine name ansa na wo save.", "保存前请输入药品名称。", "सहेजने से पहले दवा का नाम दर्ज करें।"],
    ["Pneumococcal (PCV)", "Pneumocoque (PCV)", "Neumocócica (PCV)", "Pneumococcal (PCV)", "Pneumococcal (PCV)", "Pneumococcal (PCV)", "Pneumococcal (PCV)", "Pneumococcal (PCV)", "肺炎球菌 (PCV)", "न्यूमोकोकल (PCV)"],
    ["Polio (IPV)", "Polio (VPI)", "Polio (IPV)", "Polio (IPV)", "Polio (IPV)", "Polio (IPV)", "Polio (IPV)", "Polio (IPV)", "脊灰 (IPV)", "पोलियो (IPV)"],
    ["Polio (OPV)", "Polio (VPO)", "Polio (OPV)", "Polio (OPV)", "Polio (OPV)", "Polio (OPV)", "Polio (OPV)", "Polio (OPV)", "脊灰 (OPV)", "पोलियो (OPV)"],
    ["Postpartum care", "Soins post-partum", "Cuidado posparto", "Itọju lẹhin ibimọ", "Kula da bayan haihuwa", "Nlekọta mgbe ị mụsịrị nwa", "Utunzaji baada ya kujifungua", "Postpartum care", "产后护理", "प्रसवोत्तर देखभाल"],
    ["Predicted period", "Règles prévues", "Periodo previsto", "Akoko ti a ṣe asọtẹlẹ", "Lokacin da aka hasashe", "Oge a na-atụ anya", "Hedhi inayotarajiwa", "Predicted period", "预测经期", "अनुमानित मासिक धर्म"],
    ["Predictions and logging are on hold.", "Les prévisions et l'enregistrement sont en pause.", "Las predicciones y el registro están en pausa.", "Awọn asọtẹlẹ ati iwe akọsilẹ ti duro.", "Hasashe da rubutun sun dakata.", "Amụma na ndekọ kwụsịrị.", "Utabiri na uandikishaji vimesimamishwa.", "Predictions ne logging agyina.", "预测和记录已暂停。", "भविष्यवाणियाँ और लॉगिंग रोकी गई।"],
    ["Pregnancy Tracker still has an active timeline. Resume period tracking anyway?", "Suivi de grossesse a encore une chronologie active. Reprendre le suivi des règles quand même ?", "Pregnancy Tracker aún tiene una línea de tiempo activa. ¿Reanudar el seguimiento del periodo de todos modos?", "Titele Ibimọ ni akoko ti n ṣiṣẹ. Tun bẹrẹ titẹle akoko lọna?", "Bin Diddigin Ciki har yanzu yana da tsarin lokaci mai aiki. A dawo da bin diddigin lokaci duk da haka?", "Nsochi Ime Ime ka enwe usoro oge na-arụ ọrụ. Maliteghachi nsochi oge ka ọ dị?", "Pregnancy Tracker bado ina ratiba hai. Endelea ufuatiliaji wa hedhi hata hivyo?", "Pregnancy Tracker wɔ active timeline. Resume period tracking anyway?", "怀孕追踪仍有活跃时间线。仍要恢复经期追踪？", "गर्भावस्था ट्रैकर में अभी भी सक्रिय समयरेखा है। फिर भी मासिक धर्म ट्रैकिंग फिर शुरू करें?"],
]

def main():
    batch2 = json.loads((DIR / "_apps-batch-2.json").read_text("utf-8"))
    have = json.loads((DIR / "_batch2-have.json").read_text("utf-8"))
    have_map = {row[0]: row for row in have}
    gen_map = {row[0]: row for row in GEN}

    rows = []
    missing = []
    for en in batch2:
        if en in have_map:
            rows.append(have_map[en])
        elif en in gen_map:
            rows.append(gen_map[en])
        else:
            missing.append(en)

    if missing:
        raise SystemExit(f"Missing translations for {len(missing)} strings: {missing[:5]}")

    if len(rows) != 155:
        raise SystemExit(f"Expected 155 rows, got {len(rows)}")

    for i, row in enumerate(rows):
        if len(row) != 10:
            raise SystemExit(f"Row {i+1} has {len(row)} cols: {row[0]!r}")
        if row[0] != batch2[i]:
            raise SystemExit(f"Order mismatch at {i}: {row[0]!r} != {batch2[i]!r}")

    out_lines = ["export const APPS_RAW_BATCH2 = ["]
    for row in rows:
        out_lines.append("  " + json.dumps(row, ensure_ascii=False) + ",")
    out_lines.append("];")
    out_lines.append("")

    out_path = DIR / "i18n-apps-phrases-batch2.mjs"
    out_path.write_text("\n".join(out_lines), encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {out_path.name}")

if __name__ == "__main__":
    main()
