#!/usr/bin/env node
/**
 * P2 i18n gap filler — embeds translations via phrase maps and merges locale JSON files.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

/** Optional extra phrase batches — generated by i18n-apps-phrases-batch*.mjs / i18n-p3-phrases.mjs */
async function loadExtraPhrases() {
  const extra = [];
  const modules = [
    './i18n-apps-phrases-batch1.mjs',
    './i18n-apps-phrases-batch2.mjs',
    './i18n-apps-phrases-batch3.mjs',
    './i18n-apps-phrases-batch4.mjs',
    './i18n-p3-phrases.mjs',
  ];
  for (const spec of modules) {
    try {
      const mod = await import(spec);
      for (const key of Object.keys(mod)) {
        if (key.startsWith('APPS_RAW') || key === 'P3_RAW') extra.push(...mod[key]);
      }
    } catch {
      // Batch file not generated yet — skip.
    }
  }
  return extra;
}

function mergePhrases(extraRows, PHRASES) {
  for (const row of extraRows) {
    const [en, ...vals] = row;
    LOCALES.forEach((loc, i) => {
      PHRASES[loc][en] = vals[i];
    });
  }
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const TRANS_DIR = path.join(ROOT, 'src/domains/localization/translations');
const LOCALES = ['fr', 'es', 'yo', 'ha', 'ig', 'sw', 'tw', 'zh', 'hi'];

const P3_NAMESPACES = ['emergency', 'nearby', 'learn', 'home', 'onboarding'];

/** Deep-merge overlay into base (overlay wins on conflicts). */
export function deepMerge(base, overlay) {
  if (overlay == null) return base;
  if (typeof overlay !== 'object' || Array.isArray(overlay)) return overlay;
  const out = { ...(base && typeof base === 'object' ? base : {}) };
  for (const key of Object.keys(overlay)) {
    const oVal = overlay[key];
    const bVal = out[key];
    if (
      oVal &&
      typeof oVal === 'object' &&
      !Array.isArray(oVal) &&
      bVal &&
      typeof bVal === 'object' &&
      !Array.isArray(bVal)
    ) {
      out[key] = deepMerge(bVal, oVal);
    } else {
      out[key] = oVal;
    }
  }
  return out;
}

/** Fill keys present in enTree but missing from existingTree using overlayTree. */
export function mergeMissingKeys(enTree, existingTree, overlayTree) {
  const result = deepMerge({}, existingTree ?? {});
  walk(enTree, existingTree ?? {}, overlayTree ?? {}, result);
  return result;
}

function walk(enNode, existingNode, overlayNode, outNode) {
  for (const key of Object.keys(enNode)) {
    const enVal = enNode[key];
    const existingVal = existingNode?.[key];
    const overlayVal = overlayNode?.[key];

    if (typeof enVal === 'object' && enVal !== null && !Array.isArray(enVal)) {
      if (!outNode[key] || typeof outNode[key] !== 'object' || Array.isArray(outNode[key])) {
        outNode[key] = {};
      }
      walk(enVal, existingVal, overlayVal, outNode[key]);
    } else if (existingVal === undefined && overlayVal !== undefined) {
      outNode[key] = overlayVal;
    }
  }
}

function readJson(relPath) {
  return JSON.parse(fs.readFileSync(path.join(TRANS_DIR, relPath), 'utf8'));
}

function writeJson(relPath, data) {
  const full = path.join(TRANS_DIR, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, `${JSON.stringify(data, null, 2)}\n`);
}

export function countKeys(obj) {
  let n = 0;
  for (const key of Object.keys(obj ?? {})) {
    const val = obj[key];
    if (val && typeof val === 'object' && !Array.isArray(val)) n += countKeys(val);
    else n += 1;
  }
  return n;
}

function translateValue(en, locale, PHRASES) {
  const translated = PHRASES[locale]?.[en];
  if (translated === undefined) {
    throw new Error(`Missing phrase [${locale}]: ${JSON.stringify(en).slice(0, 100)}`);
  }
  return translated;
}

function translateTree(enTree, locale, PHRASES) {
  if (typeof enTree === 'string') return translateValue(enTree, locale, PHRASES);
  const out = {};
  for (const [key, val] of Object.entries(enTree)) {
    out[key] = translateTree(val, locale, PHRASES);
  }
  return out;
}

/** Translate only keys missing from existingTree (avoids requiring phrases for already-localized strings). */
function translateMissingTree(enTree, existingTree, locale, PHRASES) {
  if (typeof enTree === 'string') {
    if (existingTree !== undefined) return undefined;
    const translated = PHRASES[locale]?.[enTree];
    return translated === undefined ? undefined : translated;
  }
  const out = {};
  for (const [key, val] of Object.entries(enTree)) {
    const translated = translateMissingTree(val, existingTree?.[key], locale, PHRASES);
    if (translated !== undefined) out[key] = translated;
  }
  return Object.keys(out).length ? out : undefined;
}

async function main() {
  const { PHRASES } = await import('./i18n-p2-phrases.mjs');
  mergePhrases(await loadExtraPhrases(), PHRASES);
  const enAuth = readJson('en/auth.json');
  const enEmergency = readJson('en/emergency.json');
  const enInsurance = readJson('en/insurance.json');
  const enProfile = readJson('en/profile.json');
  const enFamily = readJson('en/family.json');
  const enApps = readJson('en/apps.json');

  writeJson('en/auth.json', deepMerge(enAuth, {
    config: {
      supabaseTitle: 'Supabase not configured',
      supabaseMessage:
        'Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_ANON_KEY to continue with cloud auth. Local data features still work offline.',
    },
  }));
  writeJson('en/emergency.json', deepMerge(enEmergency, {
    setupWizard: {
      missingDetailsTitle: 'Missing details',
      missingDetailsMessage: 'Select blood group and genotype to continue.',
      iceContactTitle: 'ICE contact',
      iceContactRequired: 'Add name, phone, and relationship for your first emergency contact.',
    },
  }));

  const report = [];

  for (const locale of LOCALES) {
    writeJson(`${locale}/insurance.json`, translateTree(enInsurance, locale, PHRASES));

    const profileExisting = fs.existsSync(path.join(TRANS_DIR, `${locale}/profile.json`))
      ? readJson(`${locale}/profile.json`)
      : {};
    const profileOverlay = translateTree(enProfile, locale, PHRASES);
    writeJson(`${locale}/profile.json`, mergeMissingKeys(enProfile, profileExisting, profileOverlay));

    const familyExisting = fs.existsSync(path.join(TRANS_DIR, `${locale}/family.json`))
      ? readJson(`${locale}/family.json`)
      : {};
    const familyOverlay = translateTree(enFamily, locale, PHRASES);
    writeJson(`${locale}/family.json`, mergeMissingKeys(enFamily, familyExisting, familyOverlay));

    const appsExisting = readJson(`${locale}/apps.json`);
    const appsOverlay = translateMissingTree(enApps, appsExisting, locale, PHRASES) ?? {};
    writeJson(`${locale}/apps.json`, mergeMissingKeys(enApps, appsExisting, appsOverlay));

    for (const ns of P3_NAMESPACES) {
      const enTree = readJson(`en/${ns}.json`);
      const existing = readJson(`${locale}/${ns}.json`);
      const overlay = translateMissingTree(enTree, existing, locale, PHRASES) ?? {};
      writeJson(`${locale}/${ns}.json`, mergeMissingKeys(enTree, existing, overlay));
    }

    const authExisting = readJson(`${locale}/auth.json`);
    writeJson(
      `${locale}/auth.json`,
      deepMerge(authExisting, {
        config: {
          supabaseTitle: translateValue('Supabase not configured', locale, PHRASES),
          supabaseMessage: translateValue(
            'Add EXPO_PUBLIC_SUPABASE_URL and EXPO_PUBLIC_SUPABASE_ANON_KEY to continue with cloud auth. Local data features still work offline.',
            locale,
            PHRASES,
          ),
        },
      }),
    );

    const emergencyExisting = readJson(`${locale}/emergency.json`);
    writeJson(
      `${locale}/emergency.json`,
      deepMerge(emergencyExisting, {
        setupWizard: {
          missingDetailsTitle: translateValue('Missing details', locale, PHRASES),
          missingDetailsMessage: translateValue(
            'Select blood group and genotype to continue.',
            locale,
            PHRASES,
          ),
          iceContactTitle: translateValue('ICE contact', locale, PHRASES),
          iceContactRequired: translateValue(
            'Add name, phone, and relationship for your first emergency contact.',
            locale,
            PHRASES,
          ),
        },
      }),
    );

    report.push({
      locale,
      insurance: countKeys(readJson(`${locale}/insurance.json`)),
      profile: countKeys(readJson(`${locale}/profile.json`)),
      family: countKeys(readJson(`${locale}/family.json`)),
      apps: countKeys(readJson(`${locale}/apps.json`)),
      emergency: countKeys(readJson(`${locale}/emergency.json`)),
      nearby: countKeys(readJson(`${locale}/nearby.json`)),
      learn: countKeys(readJson(`${locale}/learn.json`)),
      home: countKeys(readJson(`${locale}/home.json`)),
    });
  }

  console.log('P2 i18n generation complete.\n');
  console.log('English key counts:');
  console.log(`  insurance: ${countKeys(enInsurance)}`);
  console.log(`  profile: ${countKeys(enProfile)}`);
  console.log(`  family: ${countKeys(enFamily)}`);
  console.log(`  apps: ${countKeys(enApps)}`);
  for (const ns of P3_NAMESPACES) {
    console.log(`  ${ns}: ${countKeys(readJson(`en/${ns}.json`))}`);
  }
  console.log('\nLocale coverage after merge:');
  for (const row of report) {
    console.log(
      `  ${row.locale}: insurance=${row.insurance} profile=${row.profile} family=${row.family} apps=${row.apps} emergency=${row.emergency} nearby=${row.nearby} learn=${row.learn} home=${row.home}`,
    );
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
